#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Append B1 / B2 / C1 vocabulary onto vocabulary.json"""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "src" / "data" / "vocabulary.json"

def slug(word: str) -> str:
    s = word.lower()
    for a, b in {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss",
        " ": "_", "-": "_", ".": "", "/": "_",
    }.items():
        s = s.replace(a, b)
    s = re.sub(r"[^a-z0-9_]+", "", s)
    return (s[:48] or "w")

def entry(article, word, plural, zh, cat, level, example=None, example_zh=None):
    art = None if article in (None, "-", "") else article
    pl = None if plural in (None, "-", "") else plural
    if example is None:
        if art:
            example = f"{art.capitalize()} {word} ist auf {level}-Niveau wichtig."
            example_zh = f"{art} {word}（{zh}）在 {level} 程度很重要。"
        elif cat == "動詞":
            example = f"Kannst du {word}?"
            example_zh = f"你會「{word}」（{zh}）嗎？"
        elif cat == "形容詞":
            example = f"Das ist sehr {word}."
            example_zh = f"那非常{zh}。"
        else:
            example = f"Was bedeutet {word}?"
            example_zh = f"{word} 的意思是「{zh}」。"
    return {
        "id": slug(word) + "_" + level.lower(),
        "article": art,
        "word": word,
        "translation": zh,
        "phonetic": word,
        "category": cat,
        "example": example,
        "exampleTranslation": example_zh,
        "level": level,
        **({"plural": pl} if pl else {}),
    }

# (article, word, plural, zh, category)
B1_NOUNS = [
("die","Absicht","Absichten","意圖","日常"),
("die","Achtung",None,"注意／尊敬","日常"),
("die","Angabe","Angaben","說明／資料","工作"),
("die","Annahme","Annahmen","假設／接受","日常"),
("die","Anstrengung","Anstrengungen","努力","日常"),
("die","Aufnahme","Aufnahmen","錄取／錄音","工作"),
("die","Ausnahme","Ausnahmen","例外","日常"),
("die","Aussicht","Aussichten","展望／景色","旅行"),
("die","Bedingung","Bedingungen","條件","工作"),
("die","Begegnung","Begegnungen","相遇","家庭"),
("die","Behandlung","Behandlungen","治療","日常"),
("die","Belastung","Belastungen","負擔","工作"),
("die","Bemerkung","Bemerkungen","評論","日常"),
("die","Beobachtung","Beobachtungen","觀察","日常"),
("die","Beratung","Beratungen","諮詢","工作"),
("die","Bereitschaft",None,"準備／意願","工作"),
("die","Beschäftigung","Beschäftigungen","就業／活動","工作"),
("die","Beschreibung","Beschreibungen","描述","日常"),
("die","Bestimmung","Bestimmungen","規定","工作"),
("die","Betreuung","Betreuungen","照顧","家庭"),
("die","Beurteilung","Beurteilungen","評量","工作"),
("die","Bewertung","Bewertungen","評價","工作"),
("die","Beziehung","Beziehungen","關係","家庭"),
("die","Bildung",None,"教育","工作"),
("die","Bitte","Bitten","請求","日常"),
("die","Branche","Branchen","行業","工作"),
("die","Chance","Chancen","機會","日常"),
("die","Darstellung","Darstellungen","呈現","工作"),
("die","Diskussion","Diskussionen","討論","工作"),
("die","Eigenschaft","Eigenschaften","特性","日常"),
("die","Einigung","Einigungen","協議","工作"),
("die","Einrichtung","Einrichtungen","機構／設備","日常"),
("die","Einschätzung","Einschätzungen","評估","工作"),
("die","Einstellung","Einstellungen","態度／雇用","工作"),
("die","Einwirkung","Einwirkungen","影響","日常"),
("die","Empfehlung","Empfehlungen","推薦","日常"),
("die","Entscheidung","Entscheidungen","決定","日常"),
("die","Entwicklung","Entwicklungen","發展","工作"),
("die","Erfahrung","Erfahrungen","經驗","日常"),
("die","Erfolg","Erfolge","成功","工作"),
("die","Erfindung","Erfindungen","發明","工作"),
("die","Erholung","Erholungen","休養","日常"),
("die","Erinnerung","Erinnerungen","回憶","日常"),
("die","Erklärung","Erklärungen","說明","日常"),
("die","Erlaubnis","Erlaubnisse","許可","工作"),
("die","Ermittlung","Ermittlungen","調查","工作"),
("die","Ernährung",None,"營養","飲食"),
("die","Eröffnung","Eröffnungen","開幕","日常"),
("die","Erscheinung","Erscheinungen","現象","日常"),
("die","Erwartung","Erwartungen","期待","日常"),
("die","Erweiterung","Erweiterungen","擴充","工作"),
("die","Erziehung",None,"教養","家庭"),
("die","Fähigkeit","Fähigkeiten","能力","工作"),
("die","Feststellung","Feststellungen","認定","工作"),
("die","Folge","Folgen","後果","日常"),
("die","Forderung","Forderungen","要求","工作"),
("die","Forschung","Forschungen","研究","工作"),
("die","Freiwilligkeit",None,"自願","日常"),
("die","Führung","Führungen","領導／導覽","工作"),
("die","Funktion","Funktionen","功能","日常"),
("die","Gefahr","Gefahren","危險","日常"),
("die","Gelegenheit","Gelegenheiten","機會","日常"),
("die","Gemeinde","Gemeinden","社區","日常"),
("die","Genehmigung","Genehmigungen","核准","工作"),
("die","Gesellschaft","Gesellschaften","社會","日常"),
("die","Gestaltung","Gestaltungen","設計","工作"),
("die","Gewohnheit","Gewohnheiten","習慣","日常"),
("die","Grenze","Grenzen","邊界","旅行"),
("die","Grundlage","Grundlagen","基礎","工作"),
("die","Handlung","Handlungen","行為","日常"),
("die","Herausforderung","Herausforderungen","挑戰","工作"),
("die","Herstellung","Herstellungen","製造","工作"),
("die","Hilfe","Hilfen","幫助","日常"),
("die","Hoffnung","Hoffnungen","希望","日常"),
("die","Identität","Identitäten","身分","日常"),
("die","Industrie","Industrien","工業","工作"),
("die","Information","Informationen","資訊","日常"),
("die","Innovation","Innovationen","創新","工作"),
("die","Investition","Investitionen","投資","工作"),
("die","Kenntnis","Kenntnisse","知識","工作"),
("die","Klage","Klagen","申訴","日常"),
("die","Kommunikation",None,"溝通","日常"),
("die","Kompetenz","Kompetenzen","能力","工作"),
("die","Konsequenz","Konsequenzen","後果","日常"),
("die","Kontrolle","Kontrollen","檢查","工作"),
("die","Kooperation","Kooperationen","合作","工作"),
("die","Kraft","Kräfte","力量","日常"),
("die","Krise","Krisen","危機","日常"),
("die","Kritik","Kritiken","批評","日常"),
("die","Kultur","Kulturen","文化","日常"),
("die","Leistung","Leistungen","表現","工作"),
("die","Lösung","Lösungen","解決方案","日常"),
("die","Maßnahme","Maßnahmen","措施","工作"),
("die","Möglichkeit","Möglichkeiten","可能性","日常"),
("die","Motivation","Motivationen","動機","工作"),
("die","Nachricht","Nachrichten","消息","日常"),
("die","Nachhaltigkeit",None,"永續","自然"),
("die","Öffentlichkeit",None,"公眾","日常"),
("die","Ordnung","Ordnungen","秩序","日常"),
("die","Organisation","Organisationen","組織","工作"),
("die","Persönlichkeit","Persönlichkeiten","性格","日常"),
("die","Pflege",None,"照護","日常"),
("die","Planung","Planungen","規劃","工作"),
("die","Position","Positionen","職位","工作"),
("die","Praxis","Praxen","實務","工作"),
("die","Qualität","Qualitäten","品質","日常"),
("die","Reaktion","Reaktionen","反應","日常"),
("die","Regierung","Regierungen","政府","日常"),
("die","Region","Regionen","區域","旅行"),
("die","Religion","Religionen","宗教","日常"),
("die","Ressource","Ressourcen","資源","工作"),
("die","Situation","Situationen","情況","日常"),
("die","Sorgfalt",None,"謹慎","日常"),
("die","Spannung","Spannungen","張力","日常"),
("die","Stelle","Stellen","職缺","工作"),
("die","Stimme","Stimmen","聲音","日常"),
("die","Stimmung","Stimmungen","氣氛","日常"),
("die","Störung","Störungen","干擾","日常"),
("die","Strategie","Strategien","策略","工作"),
("die","Struktur","Strukturen","結構","工作"),
("die","Teilnahme","Teilnahmen","參加","工作"),
("die","Tendenz","Tendenzen","趨勢","日常"),
("die","Übung","Übungen","練習","工作"),
("die","Umgebung","Umgebungen","環境","自然"),
("die","Umwelt",None,"環境","自然"),
("die","Unterstützung","Unterstützungen","支援","日常"),
("die","Untersuchung","Untersuchungen","檢查","日常"),
("die","Veränderung","Veränderungen","改變","日常"),
("die","Verbindung","Verbindungen","連結","日常"),
("die","Vereinbarung","Vereinbarungen","協議","工作"),
("die","Vergangenheit",None,"過去","時間"),
("die","Verhandlung","Verhandlungen","談判","工作"),
("die","Verkauf","Verkäufe","銷售","工作"),
("die","Verletzung","Verletzungen","傷害","日常"),
("die","Vermittlung","Vermittlungen","仲介","工作"),
("die","Verpflichtung","Verpflichtungen","義務","工作"),
("die","Verschmutzung","Verschmutzungen","污染","自然"),
("die","Versicherung","Versicherungen","保險","日常"),
("die","Verwaltung","Verwaltungen","行政","工作"),
("die","Vorbereitung","Vorbereitungen","準備","日常"),
("die","Voraussetzung","Voraussetzungen","前提","工作"),
("die","Vorstellung","Vorstellungen","想像","工作"),
("die","Wahrnehmung","Wahrnehmungen","知覺","日常"),
("die","Warnung","Warnungen","警告","日常"),
("die","Weiterbildung","Weiterbildungen","進修","工作"),
("die","Wirkung","Wirkungen","效果","日常"),
("die","Wirtschaft",None,"經濟","工作"),
("die","Wissenschaft","Wissenschaften","科學","工作"),
("die","Zukunft",None,"未來","時間"),
("die","Zusammenarbeit","Zusammenarbeiten","合作","工作"),
("die","Zusammenfassung","Zusammenfassungen","摘要","工作"),
("die","Zustimmung","Zustimmungen","同意","日常"),
("der","Abschnitt","Abschnitte","段落","日常"),
("der","Abschluss","Abschlüsse","結業","工作"),
("der","Abstand","Abstände","距離","日常"),
("der","Abfall","Abfälle","廢棄物","自然"),
("der","Ablauf","Abläufe","流程","工作"),
("der","Alltag",None,"日常生活","日常"),
("der","Anspruch","Ansprüche","要求","工作"),
("der","Anteil","Anteile","份額","日常"),
("der","Antrag","Anträge","申請","工作"),
("der","Aspekt","Aspekte","面向","工作"),
("der","Auftrag","Aufträge","委託","工作"),
("der","Aufwand",None,"投入","工作"),
("der","Ausdruck","Ausdrücke","表達","日常"),
("der","Ausgleich","Ausgleiche","平衡","日常"),
("der","Austausch","Austausche","交流","工作"),
("der","Bereich","Bereiche","領域","工作"),
("der","Beruf","Berufe","職業","工作"),
("der","Bescheid","Bescheide","通知","工作"),
("der","Betrieb","Betriebe","企業","工作"),
("der","Beweis","Beweise","證據","日常"),
("der","Beitrag","Beiträge","貢獻","工作"),
("der","Blick","Blicke","目光","日常"),
("der","Bürger","Bürger","公民","日常"),
("der","Charakter","Charaktere","性格","日常"),
("der","Datenschutz",None,"個資保護","工作"),
("der","Druck",None,"壓力","日常"),
("der","Eindruck","Eindrücke","印象","日常"),
("der","Einfluss","Einflüsse","影響","日常"),
("der","Einsatz","Einsätze","投入","工作"),
("der","Erwachsene","Erwachsenen","成人","家庭"),
("der","Fachmann","Fachleute","專家","工作"),
("der","Fall","Fälle","情況","日常"),
("der","Fortschritt","Fortschritte","進步","工作"),
("der","Gegner","Gegner","對手","日常"),
("der","Gegenstand","Gegenstände","物品","日常"),
("der","Gewinn","Gewinne","獲利","工作"),
("der","Grundsatz","Grundsätze","原則","工作"),
("der","Hintergrund","Hintergründe","背景","日常"),
("der","Inhalt","Inhalte","內容","日常"),
("der","Kampf","Kämpfe","鬥爭","日常"),
("der","Kandidat","Kandidaten","候選人","工作"),
("der","Kompromiss","Kompromisse","妥協","日常"),
("der","Kontakt","Kontakte","聯絡","日常"),
("der","Kunde","Kunden","客戶","工作"),
("der","Mangel","Mängel","缺乏","日常"),
("der","Markt","Märkte","市場","工作"),
("der","Mitarbeiter","Mitarbeiter","員工","工作"),
("der","Nachweis","Nachweise","證明","工作"),
("der","Nutzen",None,"益處","日常"),
("der","Partner","Partner","夥伴","家庭"),
("der","Prozess","Prozesse","過程","工作"),
("der","Rahmen","Rahmen","框架","工作"),
("der","Ratschlag","Ratschläge","忠告","日常"),
("der","Schutz",None,"保護","日常"),
("der","Schwerpunkt","Schwerpunkte","重點","工作"),
("der","Sinn","Sinne","意義","日常"),
("der","Standard","Standards","標準","工作"),
("der","Standpunkt","Standpunkte","立場","日常"),
("der","Stoff","Stoffe","材料","日常"),
("der","Streit","Streite","爭執","日常"),
("der","Teilnehmer","Teilnehmer","參與者","工作"),
("der","Umgang",None,"相處","日常"),
("der","Unterschied","Unterschiede","差異","日常"),
("der","Ursprung","Ursprünge","起源","日常"),
("der","Verbrauch",None,"消耗","日常"),
("der","Verein","Vereine","社團","日常"),
("der","Verlust","Verluste","損失","日常"),
("der","Versuch","Versuche","嘗試","日常"),
("der","Vertrag","Verträge","契約","工作"),
("der","Vorgang","Vorgänge","過程","工作"),
("der","Vortrag","Vorträge","演講","工作"),
("der","Vorteil","Vorteile","優點","日常"),
("der","Vorwurf","Vorwürfe","指責","日常"),
("der","Wandel",None,"轉變","日常"),
("der","Wunsch","Wünsche","願望","日常"),
("der","Zustand","Zustände","狀態","日常"),
("der","Zweck","Zwecke","目的","日常"),
("das","Abenteuer","Abenteuer","冒險","旅行"),
("das","Angebot","Angebote","報價","日常"),
("das","Anliegen","Anliegen","訴求","日常"),
("das","Argument","Argumente","論點","日常"),
("das","Bedürfnis","Bedürfnisse","需求","日常"),
("das","Verhalten",None,"行為","日常"),
("das","Verhältnis","Verhältnisse","關係","日常"),
("das","Verfahren","Verfahren","程序","工作"),
("das","Vergnügen","Vergnügen","樂趣","日常"),
("das","Verkehrsmittel","Verkehrsmittel","交通工具","旅行"),
("das","Vermögen","Vermögen","財產","日常"),
("das","Verständnis",None,"理解","日常"),
("das","Vertrauen",None,"信任","日常"),
("das","Vorhaben","Vorhaben","打算","日常"),
("das","Wachstum",None,"成長","工作"),
("das","Werkzeug","Werkzeuge","工具","工作"),
("das","Wissen",None,"知識","工作"),
("das","Wunder","Wunder","奇蹟","日常"),
("das","Zeichen","Zeichen","符號","日常"),
("das","Zeugnis","Zeugnisse","證明","工作"),
("das","Ziel","Ziele","目標","日常"),
("das","Thema","Themen","主題","日常"),
("das","Problem","Probleme","問題","日常"),
("das","Projekt","Projekte","專案","工作"),
("das","Ergebnis","Ergebnisse","結果","日常"),
("das","Ereignis","Ereignisse","事件","日常"),
("das","Erlebnis","Erlebnisse","經歷","日常"),
("das","Gefühl","Gefühle","感覺","日常"),
("das","Gewissen",None,"良心","日常"),
("das","Interesse","Interessen","興趣","日常"),
("das","Konzept","Konzepte","概念","工作"),
("das","Kriterium","Kriterien","標準","工作"),
("das","Medium","Medien","媒體","日常"),
("das","Mitglied","Mitglieder","成員","日常"),
("das","Modell","Modelle","模型","工作"),
("das","Niveau","Niveaus","水準","工作"),
("das","Prinzip","Prinzipien","原則","日常"),
("das","Produkt","Produkte","產品","工作"),
("das","Programm","Programme","計畫","工作"),
("das","Publikum",None,"觀眾","日常"),
("das","Recht","Rechte","權利","日常"),
("das","Risiko","Risiken","風險","日常"),
("das","System","Systeme","系統","工作"),
("das","Unternehmen","Unternehmen","企業","工作"),
]

B1_VERBS = [
("abhängen","取決於"),("ablehnen","拒絕"),("abschließen","完成"),
("ändern","改變"),("anerkennen","承認"),("ankündigen","宣布"),
("anpassen","調整"),("auffallen","引人注意"),("aufgeben","放棄"),
("aufnehmen","錄取／錄製"),("ausdrücken","表達"),("ausfallen","取消"),
("auswirken","影響"),("beantragen","申請"),("bearbeiten","處理"),
("bedienen","操作"),("beeinflussen","影響"),("beenden","結束"),
("befinden","處於"),("befürchten","擔心"),("begeistern","使熱衷"),
("begleiten","陪伴"),("behalten","保留"),("behandeln","對待"),
("behaupten","聲稱"),("beherrschen","精通"),("beitragen","貢獻"),
("benötigen","需要"),("beobachten","觀察"),("beraten","諮詢"),
("berichten","報告"),("berücksichtigen","考慮到"),("beruhigen","安撫"),
("beschäftigen","使忙碌"),("beschleunigen","加速"),("beschränken","限制"),
("beschreiben","描述"),("beseitigen","排除"),("besitzen","擁有"),
("bestehen","通過／存在"),("bestätigen","確認"),("bestimmen","決定"),
("betrachten","觀看"),("betreffen","涉及"),("betreiben","經營"),
("bewegen","移動"),("beweisen","證明"),("bewerben","應徵"),
("bezeichnen","稱作"),("beziehen","涉及"),("darstellen","呈現"),
("definieren","定義"),("diskutieren","討論"),("durchführen","執行"),
("durchsetzen","貫徹"),("einbeziehen","納入"),("einführen","引進"),
("einhalten","遵守"),("einrichten","布置"),("einschätzen","評估"),
("einsetzen","投入"),("eintreten","發生"),("empfehlen","推薦"),
("empfinden","感受"),("entfernen","移除"),("enthalten","包含"),
("entscheiden","決定"),("entsorgen","丟棄"),("entspannen","放鬆"),
("entsprechen","符合"),("entstehen","產生"),("enttäuschen","使失望"),
("entwickeln","發展"),("entwerfen","設計"),("erfahren","得知"),
("erfassen","掌握"),("erfinden","發明"),("erfordern","需要"),
("erfüllen","實現"),("ergänzen","補充"),("erhalten","獲得"),
("erholen","休養"),("erinnern","記得"),("erkennen","認出"),
("erklären","說明"),("erlauben","允許"),("erleben","經歷"),
("erledigen","辦妥"),("ermöglichen","使可能"),("ernähren","餵養"),
("erreichen","達到"),("erscheinen","出現"),("ersetzen","取代"),
("erwarten","期待"),("erwähnen","提及"),("erwerben","取得"),
("erzeugen","產生"),("erziehen","教養"),("erzielen","達成"),
("existieren","存在"),("festlegen","訂定"),("feststellen","斷定"),
("finanzieren","資助"),("fordern","要求"),("fördern","促進"),
("forschen","研究"),("fühlen","感覺"),("führen","領導"),
("fürchten","害怕"),("gestalten","塑造"),("gewinnen","贏得"),
("gründen","創立"),("handeln","行動"),("herstellen","製造"),
("hindern","阻礙"),("hinweisen","指出"),("identifizieren","辨識"),
("informieren","告知"),("interessieren","使感興趣"),("interpretieren","詮釋"),
("kämpfen","奮鬥"),("klären","澄清"),("konzentrieren","專注"),
("kritisieren","批評"),("kümmern","照顧"),("leisten","達成"),
("liefern","運送"),("lösen","解決"),("vermeiden","避免"),
("vermissen","想念"),("versprechen","答應"),("verstehen","理解"),
("versuchen","嘗試"),("verwenden","使用"),("verzeihen","原諒"),
("vorbereiten","準備"),("vorschlagen","提議"),("vorstellen","介紹"),
("wählen","選擇"),("warnen","警告"),("wechseln","更換"),
("weiterbilden","進修"),("widersprechen","反駁"),("wiederholen","重複"),
("wirken","起作用"),("wünschen","希望"),("zählen","數"),
("zeichnen","畫"),("zerstören","破壞"),("zustimmen","同意"),
("zwingen","強迫"),("überlegen","考慮"),("überraschen","使驚訝"),
("überzeugen","說服"),("überwinden","克服"),("übernehmen","接手"),
("überprüfen","檢查"),("übersetzen","翻譯"),("übertragen","傳送"),
]

B1_ADJ = [
("abhängig","依賴的"),("absolut","絕對的"),("aktiv","積極的"),
("aktuell","當前的"),("allgemein","一般的"),("allmählich","逐漸的"),
("alternativ","替代的"),("angenehm","愉快的"),("anstrengend","費力的"),
("auffällig","顯眼的"),("ausführlich","詳細的"),("ausgezeichnet","傑出的"),
("außergewöhnlich","非凡的"),("außerordentlich","特別的"),("bedeutend","重要的"),
("bedingt","有條件的"),("befürchtet","令人擔憂的"),("begeistert","熱衷的"),
("behutsam","謹慎的"),("bekannt","知名的"),("belastend","沉重的"),
("bemerkenswert","值得注意的"),("benötigt","需要的"),("berechtigt","有權的"),
("bereit","準備好的"),("beruflich","職業的"),("beschäftigt","忙碌的"),
("besorgt","擔心的"),("bestimmt","特定的"),("bewusst","有意識的"),
("bezüglich","關於的"),("billig","便宜的"),("bitter","苦的"),
("brutal","殘酷的"),("charakteristisch","典型的"),("dankbar","感激的"),
("dauerhaft","持久的"),("definitiv","確定的"),("demokratisch","民主的"),
("deutlich","清楚的"),("dringend","緊急的"),("durchschnittlich","平均的"),
("effektiv","有效的"),("ehelich","婚姻的"),("eifersüchtig","嫉妒的"),
("eigenartig","奇特的"),("eigentlich","其實的"),("eilig","匆忙的"),
("einflussreich","有影響力的"),("eindeutig","明確的"),("einfach","簡單的"),
("eingebildet","自負的"),("einheimisch","本地的"),("einmalig","獨特的"),
("einsam","孤單的"),("einstweilig","暫時的"),("einverstanden","同意的"),
("einzeln","個別的"),("ekelhaft","噁心的"),("elegant","優雅的"),
("elektrisch","電的"),("emotional","情緒的"),("empfänglich","易感的"),
("empfindlich","敏感的"),("energisch","有精力的"),("engagiert","投入的"),
("enorm","巨大的"),("entscheidend","決定性的"),("entsprechend","相應的"),
("entsetzt","驚駭的"),("entwickelt","發達的"),("erfahren","有經驗的"),
("erfolgreich","成功的"),("erforderlich","必要的"),("erfreulich","令人高興的"),
("erhältlich","可取得的"),("erstaunlich","驚人的"),("erwachsen","成年的"),
("erwartungsgemäß","如預期的"),("fachlich","專業的"),("fähig","有能力的"),
("fair","公平的"),("fantastisch","極棒的"),("fassbar","可理解的"),
("fatal","致命的"),("feierlich","隆重的"),("fertig","完成的"),
("fest","牢固的"),("feucht","潮濕的"),("flexibel","彈性的"),
("förmlich","正式的"),("freiwillig","自願的"),("freundlich","友善的"),
("friedlich","和平的"),("frisch","新鮮的"),("froh","高興的"),
("früher","以前的"),("furchtbar","可怕的"),("ganz","完全的"),
("geeignet","適合的"),("gefährlich","危險的"),("gegenüber","相對的"),
("geheim","秘密的"),("gehörig","適當的"),("geistig","精神的"),
("gelingen","成功的"),("gemäß","依照的"),("gemeinsam","共同的"),
("genau","精確的"),("genehmigt","已核准的"),("genügend","足夠的"),
("gerecht","公正的"),("gering","微小的"),("gesamt","總體的"),
("gesetzlich","法定的"),("gespannt","緊張期待的"),("gesund","健康的"),
("gewaltig","強大的"),("gewöhnlich","平常的"),("gleichgültig","漠不關心的"),
("glücklich","幸福的"),("graduell","漸進的"),("grammatikalisch","文法的"),
("großartig","了不起的"),("gründlich","徹底的"),("gültig","有效的"),
("günstig","划算的"),("häufig","頻繁的"),("heftig","激烈的"),
("heimisch","家鄉的"),("heiter","開朗的"),("hell","明亮的"),
("herausfordernd","具挑戰的"),("herrlich","美妙的"),("herzlichen","衷心的"),
("hilfreich","有幫助的"),("hintergründig","深層的"),("hoffnungsvoll","有希望的"),
("höflich","有禮貌的"),("ideal","理想的"),("identisch","相同的"),
("illegal","非法的"),("imaginär","想像的"),("individuell","個人的"),
("industriell","工業的"),("informativ","資訊豐富的"),("inhaltsreich","內容豐富的"),
("inklusiv","包容的"),("innerlich","內在的"),("innovativ","創新的"),
("intensiv","密集的"),("interessant","有趣的"),("intern","內部的"),
("international","國際的"),("intim","親密的"),("intuitiv","直覺的"),
("jährlich","每年的"),("jedenfalls","無論如何"),("jung","年輕的"),
("kalt","冷的"),("kämpferisch","好鬥的"),("kaum","幾乎不"),
("kenntnisreich","博學的"),("klar","清楚的"),("klassisch","古典的"),
("klug","聰明的"),("komisch","滑稽的"),("komplex","複雜的"),
("kompliziert","複雜的"),("konkret","具體的"),("konsequent","一貫的"),
("konservativ","保守的"),("kontinuierlich","持續的"),("konzentriert","專注的"),
("kostenlos","免費的"),("kräftig","有力的"),("krank","生病的"),
("kritisch","批判的"),("kulturell","文化的"),("künstlich","人工的"),
("kurzfristig","短期的"),("langsam","慢的"),("langweilig","無聊的"),
("laut","大聲的"),("lebendig","生動的"),("legal","合法的"),
("leicht","容易的"),("leidenschaftlich","熱情的"),("letztendlich","最終"),
("liberal","自由派的"),("lieber","寧可"),("locker","輕鬆的"),
("logisch","合乎邏輯的"),("loyal","忠誠的"),("lustig","有趣的"),
]

# B2 - more abstract / academic / professional
B2_NOUNS = [
("die","Auseinandersetzung","Auseinandersetzungen","爭論／探討","日常"),
("die","Auswirkung","Auswirkungen","影響","日常"),
("die","Bedeutung","Bedeutungen","意義","日常"),
("die","Befugnis","Befugnisse","權限","工作"),
("die","Bekanntmachung","Bekanntmachungen","公告","工作"),
("die","Belastbarkeit",None,"抗壓性","工作"),
("die","Bereicherung","Bereicherungen","充實","日常"),
("die","Beschleunigung","Beschleunigungen","加速","工作"),
("die","Beschränkung","Beschränkungen","限制","工作"),
("die","Betrachtung","Betrachtungen","考察","日常"),
("die","Bevölkerungsentwicklung",None,"人口發展","日常"),
("die","Beweislast",None,"舉證責任","工作"),
("die","Bewusstheit",None,"覺察","日常"),
("die","Bildungschance","Bildungschancen","教育機會","工作"),
("die","Datenverarbeitung",None,"資料處理","工作"),
("die","Differenzierung","Differenzierungen","區分","工作"),
("die","Diversität",None,"多元","日常"),
("die","Durchführung","Durchführungen","實施","工作"),
("die","Effizienz",None,"效率","工作"),
("die","Einbeziehung",None,"納入","工作"),
("die","Einflussnahme","Einflussnahmen","施加影響","日常"),
("die","Einschränkung","Einschränkungen","限制","日常"),
("die","Einstellungssache",None,"態度問題","日常"),
("die","Energieversorgung",None,"能源供應","自然"),
("die","Entfremdung",None,"疏離","日常"),
("die","Entlastung","Entlastungen","減輕負擔","工作"),
("die","Entscheidungsfindung",None,"決策","工作"),
("die","Enttäuschung","Enttäuschungen","失望","日常"),
("die","Erkenntnis","Erkenntnisse","認識","工作"),
("die","Erleichterung","Erleichterungen","減輕","日常"),
("die","Ermächtigung","Ermächtigungen","授權","工作"),
("die","Erschöpfung",None,"精疲力竭","日常"),
("die","Erweiterung","Erweiterungen","擴展","工作"),
("die","Fachkenntnis","Fachkenntnisse","專業知識","工作"),
("die","Fairness",None,"公平","日常"),
("die","Fehleinschätzung","Fehleinschätzungen","誤判","日常"),
("die","Flexibilität",None,"彈性","工作"),
("die","Forschungsergebnis","Forschungsergebnisse","研究成果","工作"),
("die","Fragestellung","Fragestellungen","問題設定","工作"),
("die","Freiheit","Freiheiten","自由","日常"),
("die","Gerechtigkeit",None,"正義","日常"),
("die","Gesamtbewertung","Gesamtbewertungen","總評","工作"),
("die","Gesundheitspolitik",None,"衛生政策","日常"),
("die","Glaubwürdigkeit",None,"可信度","日常"),
("die","Gleichberechtigung",None,"平等權利","日常"),
("die","Globalisierung",None,"全球化","日常"),
("die","Handlungsfähigkeit",None,"行動能力","工作"),
("die","Herausforderung","Herausforderungen","挑戰","工作"),
("die","Hilflosigkeit",None,"無助","日常"),
("die","Hinterfragung","Hinterfragungen","質疑","日常"),
("die","Identifizierung","Identifizierungen","識別","工作"),
("die","Immobilie","Immobilien","不動產","家庭"),
("die","Individualität",None,"個體性","日常"),
("die","Informationsquelle","Informationsquellen","資訊來源","日常"),
("die","Initiative","Initiativen","倡議","工作"),
("die","Integration","Integrationen","整合","日常"),
("die","Intensität","Intensitäten","強度","日常"),
("die","Interaktion","Interaktionen","互動","日常"),
("die","Interpretation","Interpretationen","詮釋","工作"),
("die","Investition","Investitionen","投資","工作"),
("die","Karriere","Karrieren","職涯","工作"),
("die","Klimaveränderung","Klimaveränderungen","氣候變遷","自然"),
("die","Komplexität",None,"複雜性","日常"),
("die","Konfliktlösung","Konfliktlösungen","衝突解決","日常"),
("die","Konjunktur",None,"景氣","工作"),
("die","Konkurrenz",None,"競爭","工作"),
("die","Konstruktivität",None,"建設性","工作"),
("die","Konsumgesellschaft",None,"消費社會","日常"),
("die","Kontinuität",None,"連續性","工作"),
("die","Konzentration","Konzentrationen","專注","日常"),
("die","Koordinierung","Koordinierungen","協調","工作"),
("die","Kreativität",None,"創造力","工作"),
("die","Kundenbindung",None,"客戶忠誠","工作"),
("die","Lebensqualität",None,"生活品質","日常"),
("die","Legitimation","Legitimationen","正當性","工作"),
("die","Leistungsfähigkeit",None,"效能","工作"),
("die","Loyalität",None,"忠誠","日常"),
("die","Machbarkeit",None,"可行性","工作"),
("die","Marktanalyse","Marktanalysen","市場分析","工作"),
("die","Medienkompetenz",None,"媒體素養","日常"),
("die","Meinungsverschiedenheit","Meinungsverschiedenheiten","意見不合","日常"),
("die","Menschenwürde",None,"人的尊嚴","日常"),
("die","Mobilität",None,"流動性","旅行"),
("die","Nachhaltigkeit",None,"永續性","自然"),
("die","Netzwerkpflege",None,"人脈維護","工作"),
("die","Objektivität",None,"客觀性","日常"),
("die","Orientierung","Orientierungen","定向","日常"),
("die","Perspektive","Perspektiven","視角","日常"),
("die","Priorität","Prioritäten","優先","工作"),
("die","Problemlösung","Problemlösungen","問題解決","日常"),
("die","Produktivität",None,"生產力","工作"),
("die","Professionalität",None,"專業度","工作"),
("die","Prognose","Prognosen","預測","工作"),
("die","Rahmenbedingung","Rahmenbedingungen","框架條件","工作"),
("die","Rationalität",None,"理性","日常"),
("die","Rechtfertigung","Rechtfertigungen","辯護","日常"),
("die","Rechtsprechung",None,"判例","工作"),
("die","Relevanz",None,"相關性","日常"),
("die","Rentabilität",None,"獲利能力","工作"),
("die","Repräsentation","Repräsentationen","代表","工作"),
("die","Resistenz","Resistenzen","抗性","日常"),
("die","Respektlosigkeit",None,"不敬","日常"),
("die","Ressourcenschonung",None,"節約資源","自然"),
("die","Rücksichtnahme",None,"顧慮","日常"),
("die","Sachkenntnis","Sachkenntnisse","專業素養","工作"),
("die","Selbstbestimmung",None,"自主","日常"),
("die","Selbstständigkeit",None,"獨立","工作"),
("die","Sensibilität",None,"敏感度","日常"),
("die","Sichtweise","Sichtweisen","觀點","日常"),
("die","Solidarität",None,"團結","日常"),
("die","Sozialversicherung",None,"社會保險","工作"),
("die","Spezialisierung","Spezialisierungen","專門化","工作"),
("die","Stabilität",None,"穩定","日常"),
("die","Stellungnahme","Stellungnahmen","聲明","工作"),
("die","Subjektivität",None,"主觀性","日常"),
("die","Sustainability",None,"永續（英）","自然"),
("die","Symbolik",None,"象徵","日常"),
("die","Tagesordnung","Tagesordnungen","議程","工作"),
("die","Teamarbeit",None,"團隊合作","工作"),
("die","Technologie","Technologien","科技","工作"),
("die","Toleranz",None,"寬容","日常"),
("die","Transparenz",None,"透明","工作"),
("die","Überzeugung","Überzeugungen","信念","日常"),
("die","Umsetzung","Umsetzungen","落實","工作"),
("die","Unabhängigkeit",None,"獨立","日常"),
("die","Verantwortung","Verantwortungen","責任","日常"),
("die","Verfügbarkeit",None,"可用性","工作"),
("die","Vergleichbarkeit",None,"可比性","工作"),
("die","Verlässlichkeit",None,"可靠","日常"),
("die","Vernetzung","Vernetzungen","聯網","工作"),
("die","Veröffentlichung","Veröffentlichungen","出版","工作"),
("die","Verschlechterung","Verschlechterungen","惡化","日常"),
("die","Verständigung","Verständigungen","諒解","日常"),
("die","Verwirklichung","Verwirklichungen","實現","日常"),
("die","Vielfalt",None,"多元","日常"),
("die","Vollständigkeit",None,"完整性","日常"),
("die","Vorhersage","Vorhersagen","預測","日常"),
("die","Wahrhaftigkeit",None,"真誠","日常"),
("die","Wechselwirkung","Wechselwirkungen","交互作用","日常"),
("die","Wertschätzung",None,"重視","日常"),
("die","Wettbewerbsfähigkeit",None,"競爭力","工作"),
("die","Wirksamkeit",None,"有效性","工作"),
("die","Wirtschaftlichkeit",None,"經濟效益","工作"),
("die","Wissenschaftlichkeit",None,"科學性","工作"),
("die","Zielsetzung","Zielsetzungen","目標設定","工作"),
("die","Zufriedenheit",None,"滿意","日常"),
("die","Zuverlässigkeit",None,"可靠度","日常"),
("der","Abbau",None,"削減","工作"),
("der","Abfallstoff","Abfallstoffe","廢棄物","自然"),
("der","Abschlussbericht","Abschlussberichte","結案報告","工作"),
("der","Abstraktionsgrad",None,"抽象程度","工作"),
("der","Anreiz","Anreize","誘因","工作"),
("der","Ansatz","Ansätze","途徑","工作"),
("der","Anspruch","Ansprüche","主張","工作"),
("der","Arbeitsmarkt",None,"勞動市場","工作"),
("der","Aspekt","Aspekte","面向","日常"),
("der","Aufschwung",None,"復甦","工作"),
("der","Ausbau",None,"擴建","工作"),
("der","Ausgleich","Ausgleiche","補償","日常"),
("der","Auslöser","Auslöser","觸發因素","日常"),
("der","Begriff","Begriffe","概念","日常"),
("der","Beitrag","Beiträge","文章／貢獻","工作"),
("der","Belastungsfaktor","Belastungsfaktoren","壓力因子","日常"),
("der","Bericht","Berichte","報告","工作"),
("der","Beschluss","Beschlüsse","決議","工作"),
("der","Bestandteil","Bestandteile","組成部分","日常"),
("der","Betrieb","Betriebe","營運","工作"),
("der","Bezug","Bezüge","關聯","日常"),
("der","Branchenwechsel",None,"轉行","工作"),
("der","Bürgersteig","Bürgersteige","人行道","旅行"),
("der","Datenaustausch",None,"資料交換","工作"),
("der","Diskurs","Diskurse","論述","日常"),
("der","Durchschnitt","Durchschnitte","平均","數字"),
("der","Ehrgeiz",None,"野心","日常"),
("der","Einwand","Einwände","異議","日常"),
("der","Entwurf","Entwürfe","草案","工作"),
("der","Erfolg","Erfolge","成功","工作"),
("der","Erkenntnisgewinn",None,"認知收穫","工作"),
("der","Fachkräftemangel",None,"專業人力短缺","工作"),
("der","Faktor","Faktoren","因素","日常"),
("der","Fortschritt","Fortschritte","進展","工作"),
("der","Gegensatz","Gegensätze","對立","日常"),
("der","Gesichtspunkt","Gesichtspunkte","觀點","日常"),
("der","Handlungsspielraum","Handlungsspielräume","行動空間","工作"),
("der","Hintergrund","Hintergründe","背景","日常"),
("der","Impuls","Impulse","衝動／動力","日常"),
("der","Indikator","Indikatoren","指標","工作"),
("der","Klimawandel",None,"氣候變遷","自然"),
("der","Konflikt","Konflikte","衝突","日常"),
("der","Konsens",None,"共識","日常"),
("der","Kontext","Kontexte","脈絡","日常"),
("der","Kreis","Kreise","圈子","日常"),
("der","Lebenslauf","Lebensläufe","履歷","工作"),
("der","Leitgedanke","Leitgedanken","主導思想","工作"),
("der","Mangel","Mängel","不足","日常"),
("der","Maßstab","Maßstäbe","尺規","日常"),
("der","Mehrwert",None,"附加價值","工作"),
("der","Missstand","Missstände","弊端","日常"),
("der","Nachteil","Nachteile","缺點","日常"),
("der","Nutzen",None,"效益","日常"),
("der","Rahmen","Rahmen","框架","工作"),
("der","Sachverhalt","Sachverhalte","事實情況","工作"),
("der","Schwerpunkt","Schwerpunkte","重點","工作"),
("der","Standpunkt","Standpunkte","立場","日常"),
("der","Stellenwert",None,"地位","日常"),
("der","Stoffwechsel",None,"新陳代謝","日常"),
("der","Tagesablauf","Tagesabläufe","作息","時間"),
("der","Übergang","Übergänge","過渡","日常"),
("der","Umgang",None,"處理方式","日常"),
("der","Unterschied","Unterschiede","差別","日常"),
("der","Ursprung","Ursprünge","起源","日常"),
("der","Vergleich","Vergleiche","比較","日常"),
("der","Verlust","Verluste","損失","日常"),
("der","Verstoß","Verstöße","違規","工作"),
("der","Versuch","Versuche","試驗","日常"),
("der","Vorgang","Vorgänge","程序","工作"),
("der","Vorwurf","Vorwürfe","指責","日常"),
("der","Wandel",None,"變遷","日常"),
("der","Wettbewerb","Wettbewerbe","競爭","工作"),
("der","Widerstand","Widerstände","阻力","日常"),
("der","Zusammenhang","Zusammenhänge","關聯","日常"),
("der","Zweck","Zwecke","目的","日常"),
("das","Abkommen","Abkommen","協定","工作"),
("das","Anliegen","Anliegen","訴求","日常"),
("das","Ansehen",None,"聲望","日常"),
("das","Argument","Argumente","論據","日常"),
("das","Bewusstsein",None,"意識","日常"),
("das","Defizit","Defizite","赤字／不足","工作"),
("das","Dilemma","Dilemmata","兩難","日常"),
("das","Einkommen","Einkommen","收入","工作"),
("das","Engagement",None,"投入","工作"),
("das","Ergebnis","Ergebnisse","成果","日常"),
("das","Gutachten","Gutachten","鑑定報告","工作"),
("das","Hindernis","Hindernisse","障礙","日常"),
("das","Indiz","Indizien","跡象","日常"),
("das","Kriterium","Kriterien","準則","工作"),
("das","Konzept","Konzepte","構想","工作"),
("das","Merkmal","Merkmale","特徵","日常"),
("das","Missverständnis","Missverständnisse","誤會","日常"),
("das","Netzwerk","Netzwerke","網絡","工作"),
("das","Phänomen","Phänomene","現象","日常"),
("das","Potenzial","Potenziale","潛力","工作"),
("das","Prinzip","Prinzipien","原則","日常"),
("das","Problem","Probleme","難題","日常"),
("das","Profil","Profile","形象","工作"),
("das","Risiko","Risiken","風險","日常"),
("das","Schema","Schemata","模式","日常"),
("das","Spektrum","Spektren","範圍","日常"),
("das","Szenario","Szenarien","情境","工作"),
("das","Thema","Themen","議題","日常"),
("das","Übel","Übel","弊病","日常"),
("das","Verfahren","Verfahren","程序","工作"),
("das","Verhalten",None,"行為","日常"),
("das","Verhältnis","Verhältnisse","關係","日常"),
("das","Vermögen","Vermögen","資產","日常"),
("das","Verständnis",None,"理解","日常"),
("das","Vertrauen",None,"信任","日常"),
("das","Vorhaben","Vorhaben","計畫","日常"),
("das","Wachstum",None,"成長","工作"),
("das","Werkzeug","Werkzeuge","工具","工作"),
("das","Wissen",None,"知識","工作"),
("das","Ziel","Ziele","目標","日常"),
]

B2_VERBS = [
("abschätzen","估計"),("abwägen","權衡"),("analysieren","分析"),
("argumentieren","論證"),("ausarbeiten","擬定"),("auseinandersetzen","探討"),
("auswerten","評析"),("beanstanden","提出異議"),("beeinflussen","影響"),
("begründen","論證理由"),("behaupten","斷言"),("bekräftigen","強調"),
("bemängeln","指責缺點"),("berücksichtigen","顧及"),("beschleunigen","加速"),
("beschränken","限制"),("bestätigen","證實"),("betonen","強調"),
("beurteilen","評斷"),("bewältigen","應付"),("beweisen","證明"),
("beziehen","引用／關聯"),("darlegen","闡述"),("differenzieren","區分"),
("diskutieren","討論"),("durchschauen","看穿"),("einbeziehen","納入"),
("einschätzen","評估"),("einschränken","限制"),("einwenden","提出異議"),
("empfehlen","推薦"),("entgegenwirken","對抗"),("entscheiden","裁決"),
("entwickeln","發展"),("erarbeiten","研擬"),("erfahren","體驗"),
("erfassen","掌握"),("erfordern","要求"),("erfüllen","滿足"),
("ergänzen","補充"),("ergründen","探究"),("erhalten","維持"),
("erkennen","認知"),("erläutern","闡釋"),("ermöglichen","促成"),
("erreichen","達成"),("erschließen","開拓"),("erwarten","預期"),
("erwähnen","提及"),("erweitern","擴展"),("erzeugen","產生"),
("evaluieren","評估"),("feststellen","確認"),("folgerichtig","合理推論"),
("formulieren","表述"),("fördern","促進"),("fundieren","奠定基礎"),
("garantieren","保證"),("gegenüberstellen","對照"),("gestalten","塑造"),
("hervorheben","突顯"),("hinterfragen","質疑"),("hinweisen","指出"),
("identifizieren","識別"),("illustrieren","說明"),("implizieren","暗含"),
("informieren","告知"),("integrieren","整合"),("interpretieren","詮釋"),
("investieren","投資"),("kritisieren","批評"),("konzentrieren","集中"),
("koordinieren","協調"),("lösen","解決"),("nachweisen","證明"),
("optimieren","優化"),("orientieren","導向"),("planen","規劃"),
("präzisieren","精確化"),("priorisieren","排優先"),("prognostizieren","預測"),
("prüfen","檢視"),("realisieren","實現"),("reduzieren","減少"),
("reflektieren","反思"),("relativieren","相對化"),("respektieren","尊重"),
("resultieren","導致"),("schätzen","估計"),("schildern","描述"),
("schließen","推論"),("simulieren","模擬"),("spezifizieren","具體化"),
("stabilisieren","穩定"),("steigern","提升"),("stellen","提出"),
("strukturieren","結構化"),("substituieren","取代"),("summarisieren","總結"),
("systematisieren","系統化"),("thematisieren","主題化"),("überdenken","重新思考"),
("überprüfen","覆核"),("überraschen","使驚訝"),("übertragen","轉移"),
("überwinden","克服"),("überzeugen","說服"),("umsetzen","落實"),
("unterscheiden","區別"),("unterstützen","支持"),("untersuchen","研究"),
("verallgemeinern","概括"),("verändern","改變"),("veranschaulichen","具體說明"),
("verantwortlich","負責"),("verbessern","改善"),("verdeutlichen","澄清"),
("vereinbaren","約定"),("verfolgen","追蹤"),("vergleichen","比較"),
("vermeiden","避免"),("vermitteln","傳達"),("verpflichten","使負義務"),
("versagen","失敗"),("verschärfen","加劇"),("verschlechtern","惡化"),
("verstehen","理解"),("verteidigen","辯護"),("vertiefen","深化"),
("verwirklichen","實現"),("verzichten","放棄"),("vollziehen","執行"),
("voraussetzen","預設"),("vorhaben","打算"),("vorhersagen","預言"),
("wahrnehmen","察覺"),("weiterentwickeln","繼續發展"),("widersprechen","反駁"),
("wiederholen","重申"),("wirken","產生作用"),("zurückführen","歸因"),
("zusammenfassen","總結"),("zustimmen","贊同"),("zweckmäßig","合目的"),
]

B2_ADJ = [
("abstrakt","抽象的"),("aktuell","最新的"),("angemessen","適當的"),
("ansehnlich","可觀的"),("anschließend","隨後的"),("anspruchsvoll","高要求的"),
("auffallend","顯著的"),("ausführlich","詳盡的"),("ausreichend","充足的"),
("außerordentlich","非凡的"),("bedeutsam","意義重大的"),("belastbar","抗壓的"),
("bemerkenswert","值得注意的"),("berufsbezogen","與職業相關的"),("bewusst","有意識的"),
("charakteristisch","典型的"),("differenziert","有區分的"),("durchgreifend","徹底的"),
("effizient","有效率的"),("eindeutig","明確的"),("einflussreich","有影響力的"),
("einschließlich","包括的"),("elementar","基本的"),("entscheidend","關鍵的"),
("entsprechend","相應的"),("erforderlich","必要的"),("erheblich","可觀的"),
("erkennbar","可辨的"),("ersichtlich","明顯的"),("essentiell","本質的"),
("exemplarisch","範例性的"),("fachkundig","內行的"),("faktisch","事實上的"),
("folgerichtig","合乎邏輯的"),("fundamental","根本的"),("ganzheitlich","整體的"),
("geeignet","合適的"),("gemeinhin","一般地"),("genau","精確的"),
("gerechtfertigt","合理的"),("global","全球的"),("grundlegend","基礎的"),
("häufig","常見的"),("hinreichend","充分的"),("hypothetisch","假設的"),
("identisch","同一的"),("implizit","隱含的"),("individuell","個人的"),
("inhaltlich","內容上的"),("innovativ","創新的"),("intensiv","密集的"),
("interessant","有趣的"),("intern","內部的"),("interpretierbar","可詮釋的"),
("komplex","複雜的"),("konkret","具體的"),("konsequent","一貫的"),
("konstruktiv","建設性的"),("kontinuierlich","連續的"),("kontrovers","有爭議的"),
("konventionell","傳統的"),("kritisch","批判的"),("kurzfristig","短期的"),
("langfristig","長期的"),("maßgeblich","決定性的"),("methodisch","方法上的"),
("nachhaltig","永續的"),("nachvollziehbar","可理解的"),("objektiv","客觀的"),
("offensichtlich","明顯的"),("optional","可選的"),("originell","獨創的"),
("parallel","平行的"),("partial","部分的"),("persönlich","個人的"),
("potentiell","潛在的"),("praktisch","實務的"),("präzise","精確的"),
("primär","主要的"),("problematisch","有問題的"),("produktiv","有生產力的"),
("professionell","專業的"),("progressiv","進步的"),("proportional","成比例的"),
("qualitativ","質性的"),("quantitativ","量化的"),("rational","理性的"),
("realistisch","現實的"),("relevant","相關的"),("repräsentativ","代表性的"),
("ressourcenorientiert","資源導向的"),("rücksichtsvoll","體諒的"),("sachlich","客觀的"),
("selbstständig","自主的"),("signifikant","顯著的"),("spezifisch","特定的"),
("stabil","穩定的"),("strategisch","策略的"),("strukturell","結構性的"),
("subjektiv","主觀的"),("substantiell","實質的"),("systematisch","系統的"),
("theoretisch","理論的"),("transparent","透明的"),("typisch","典型的"),
("übergreifend","跨領域的"),("überraschend","令人意外的"),("überzeugend","有說服力的"),
("umfassend","全面的"),("umweltfreundlich","環保的"),("unabhängig","獨立的"),
("unbedingt","絕對的"),("unentbehrlich","不可或缺的"),("unerlässlich","必要的"),
("unmittelbar","直接的"),("unterschiedlich","不同的"),("verantwortlich","負責的"),
("verbindlich","具約束力的"),("vergleichbar","可比較的"),("verlässlich","可靠的"),
("verständlich","易懂的"),("vertraut","熟悉的"),("vielseitig","多方面的"),
("vollständig","完整的"),("voraussichtlich","預計的"),("vorläufig","暫時的"),
("wesentlich","本質的"),("wichtig","重要的"),("wirtschaftlich","經濟的"),
("wissenschaftlich","科學的"),("zeitgemäß","符合時代的"),("zielgerichtet","有目標的"),
("zufriedenstellend","令人滿意的"),("zusätzlich","額外的"),("zuverlässig","可靠的"),
("zweckmäßig","合宜的"),("zweifellos","無疑的"),
]

# C1 - advanced academic / nuanced
C1_NOUNS = [
("die","Auseinandersetzung","Auseinandersetzungen","深入探討","日常"),
("die","Ambivalenz","Ambivalenzen","矛盾情感","日常"),
("die","Analogie","Analogien","類比","工作"),
("die","Annahme","Annahmen","假設","工作"),
("die","Antithese","Antithesen","反題","工作"),
("die","Ausdifferenzierung","Ausdifferenzierungen","細分","工作"),
("die","Bedeutsamkeit",None,"重要性","日常"),
("die","Begriffsbildung",None,"概念形成","工作"),
("die","Belegstelle","Belegstellen","引證處","工作"),
("die","Betrachtungsweise","Betrachtungsweisen","觀察方式","日常"),
("die","Bewusstseinsbildung",None,"意識形塑","日常"),
("die","Chancengleichheit",None,"機會平等","日常"),
("die","Datenlage",None,"數據現況","工作"),
("die","Deutung","Deutungen","詮釋","工作"),
("die","Diskrepanz","Diskrepanzen","落差","日常"),
("die","Diskursanalyse","Diskursanalysen","論述分析","工作"),
("die","Einflussnahme","Einflussnahmen","影響力運作","日常"),
("die","Einsicht","Einsichten","洞見","日常"),
("die","Empirie",None,"經驗研究","工作"),
("die","Erkenntnistheorie",None,"認識論","工作"),
("die","Erwägung","Erwägungen","考量","日常"),
("die","Evidenz",None,"證據力","工作"),
("die","Exzellenz",None,"卓越","工作"),
("die","Fachdiskussion","Fachdiskussionen","專業討論","工作"),
("die","Gedankenführung",None,"思路","工作"),
("die","Gegenüberstellung","Gegenüberstellungen","對照","日常"),
("die","Glaubwürdigkeit",None,"可信度","日常"),
("die","Handlungskompetenz","Handlungskompetenzen","行動能力","工作"),
("die","Herangehensweise","Herangehensweisen","切入方式","工作"),
("die","Implikation","Implikationen","意涵","工作"),
("die","Induktion",None,"歸納","工作"),
("die","Interdependenz","Interdependenzen","相互依賴","日常"),
("die","Introspektion",None,"內省","日常"),
("die","Kohärenz",None,"連貫性","工作"),
("die","Komplexitätsreduktion",None,"複雜度簡化","工作"),
("die","Konnotation","Konnotationen","隱含意義","日常"),
("die","Konsistenz",None,"一致性","工作"),
("die","Konstrukt","Konstrukte","建構","工作"),
("die","Kontroverse","Kontroversen","爭議","日常"),
("die","Kritikfähigkeit",None,"批判能力","工作"),
("die","Lebenswirklichkeit",None,"生活現實","日常"),
("die","Leitdifferenz","Leitdifferenzen","主導差異","工作"),
("die","Methodik",None,"方法論","工作"),
("die","Nachvollziehbarkeit",None,"可理解性","日常"),
("die","Nuance","Nuancen","細微差別","日常"),
("die","Paradoxie","Paradoxien","悖論","日常"),
("die","Perspektivität",None,"視角性","日常"),
("die","Plausibilität",None,"可信性","日常"),
("die","Prämisse","Prämissen","前提","工作"),
("die","Problematik",None,"問題性","日常"),
("die","Prozesshaftigkeit",None,"過程性","工作"),
("die","Rationalität",None,"理性","日常"),
("die","Relevanz",None,"關聯性","日常"),
("die","Resilienz",None,"韌性","日常"),
("die","Schlussfolgerung","Schlussfolgerungen","結論","工作"),
("die","Selbstreflexion",None,"自我反思","日常"),
("die","Sinnstiftung",None,"意義賦予","日常"),
("die","Sozialisation",None,"社會化","日常"),
("die","Spezifik",None,"特殊性","工作"),
("die","Stichhaltigkeit",None,"站得住腳","工作"),
("die","Stringenz",None,"嚴謹","工作"),
("die","Synthese","Synthesen","綜合","工作"),
("die","Systematik",None,"系統性","工作"),
("die","Theoriebildung",None,"理論建構","工作"),
("die","These","Thesen","論題","工作"),
("die","Tragweite",None,"影響範圍","日常"),
("die","Überlegung","Überlegungen","思索","日常"),
("die","Unschärfe",None,"模糊性","日常"),
("die","Ursächlichkeit",None,"因果性","日常"),
("die","Verallgemeinerung","Verallgemeinerungen","概括","工作"),
("die","Verantwortungsethik",None,"責任倫理","日常"),
("die","Verflechtung","Verflechtungen","交織","日常"),
("die","Vermittlung","Vermittlungen","中介","工作"),
("die","Vorannahme","Vorannahmen","預設","工作"),
("die","Wechselwirkung","Wechselwirkungen","交互作用","日常"),
("die","Widersprüchlichkeit",None,"矛盾性","日常"),
("die","Wirkmächtigkeit",None,"影響力","日常"),
("die","Zuverlässigkeit",None,"可靠性","日常"),
("der","Ansatzpunkt","Ansatzpunkte","切入點","工作"),
("der","Begriffsapparat",None,"概念工具","工作"),
("der","Beleg","Belege","佐證","工作"),
("der","Blickwinkel","Blickwinkel","角度","日常"),
("der","Diskurs","Diskurse","論述","日常"),
("der","Erkenntnisgewinn",None,"認知收穫","工作"),
("der","Gegenentwurf","Gegenentwürfe","替代方案","工作"),
("der","Grundsatz","Grundsätze","原則","工作"),
("der","Handlungsrahmen",None,"行動框架","工作"),
("der","Interpretationsspielraum","Interpretationsspielräume","詮釋空間","工作"),
("der","Kern","Kerne","核心","日常"),
("der","Leitbegriff","Leitbegriffe","核心概念","工作"),
("der","Nachweis","Nachweise","論證依據","工作"),
("der","Paradigmenwechsel",None,"典範轉移","工作"),
("der","Sachverhalt","Sachverhalte","事實狀態","工作"),
("der","Stellenwert",None,"分量","日常"),
("der","Stoff","Stoffe","題材","日常"),
("der","Umbruch","Umbrüche","劇變","日常"),
("der","Zugang","Zugänge","取徑","工作"),
("der","Zusammenhang","Zusammenhänge","脈絡關聯","日常"),
("das","Abbild","Abbilder","映照","日常"),
("das","Argumentationsmuster","Argumentationsmuster","論證模式","工作"),
("das","Gedankengut",None,"思想內容","日常"),
("das","Konstrukt","Konstrukte","建構物","工作"),
("das","Leitmotiv","Leitmotive","主旋律","日常"),
("das","Merkmal","Merkmale","特徵","日常"),
("das","Narrativ","Narrative","敘事","日常"),
("das","Phänomen","Phänomene","現象","日常"),
("das","Potenzial","Potenziale","潛能","工作"),
("das","Spannungsfeld","Spannungsfelder","張力場域","日常"),
("das","Spektrum","Spektren","光譜","日常"),
("das","Untersuchungsdesign","Untersuchungsdesigns","研究設計","工作"),
("das","Verfahren","Verfahren","方法程序","工作"),
("das","Verhältnis","Verhältnisse","關係結構","日常"),
("das","Verständnis",None,"理解深度","日常"),
]

C1_VERBS = [
("abschätzen","估量"),("abwägen","權衡"),("analysieren","分析"),
("antizipieren","預見"),("argumentieren","論證"),("artikulieren","清楚表達"),
("auseinandersetzen","深入探討"),("ausloten","摸清底細"),("ausweisen","證明／顯示"),
("begründen","提出理由"),("beleuchten","闡明"),("beurteilen","評斷"),
("darlegen","詳述"),("deduzieren","演繹"),("differenzieren","細分"),
("einordnen","歸類"),("elaborieren","詳盡闡發"),("ergründen","徹查"),
("erläutern","闡釋"),("erörtern","討論"),("evaluieren","評鑑"),
("exzerpieren","摘錄"),("fundieren","奠基"),("generalisieren","概括"),
("hinterfragen","質疑"),("illustrieren","例證"),("implizieren","暗示"),
("induzieren","歸納導出"),("inferieren","推論"),("interpretieren","詮釋"),
("klassifizieren","分類"),("konkretisieren","具體化"),("konstruieren","建構"),
("kontrastieren","對比"),("kritisieren","批評"),("modifizieren","修改"),
("nuancieren","細緻區分"),("operationalisieren","操作化"),("problematisieren","問題化"),
("prognostizieren","預測"),("reflektieren","反思"),("relativieren","相對化"),
("rekonstruieren","重建"),("resümieren","總結"),("revidieren","修正"),
("schildern","細描"),("schlussfolgern","下結論"),("spezifizieren","具體指明"),
("strukturieren","結構化"),("subsumieren","歸入"),("synthetisieren","綜合"),
("thematisieren","作為主題"),("überdenken","重新思考"),("untermauern","佐證"),
("unterscheiden","區辨"),("verallgemeinern","普遍化"),("verdeutlichen","澄清"),
("vergegenwärtigen","使想起"),("verknüpfen","連結"),("vermitteln","傳達"),
("verselbstständigen","使自主"),("vertiefen","深化"),("voraussetzen","預設"),
("wahrnehmen","覺察"),("weiterdenken","繼續思考"),("widersprechen","反駁"),
("zurückführen","歸因於"),("zusammenfassen","總結"),("zuschreiben","歸屬"),
]

C1_ADJ = [
("ambivalent","矛盾的"),("analog","類比的"),("anstrengend","吃力的"),
("argumentativ","論證性的"),("ausdifferenziert","細分的"),("bedeutsam","重大的"),
("begrifflich","概念性的"),("belegbar","可證明的"),("differenziert","有層次的"),
("diskursiv","論述性的"),("eigenständig","自主的"),("empirisch","經驗的"),
("epistemisch","認識論的"),("erklärungsbedürftig","需要解釋的"),("evident","顯而易見的"),
("explizit","明確的"),("fundiert","有根據的"),("ganzheitlich","整體的"),
("hermeneutisch","詮釋學的"),("hypothetisch","假設的"),("implizit","隱含的"),
("induktiv","歸納的"),("inkohärent","不連貫的"),("interdisziplinär","跨領域的"),
("interpretativ","詮釋性的"),("kohärent","連貫的"),("komplex","複雜的"),
("konsistent","一致的"),("kontrovers","有爭議的"),("kritisch","批判的"),
("methodisch","方法嚴謹的"),("nachvollziehbar","可理解的"),("nuancenreich","層次豐富的"),
("paradox","悖論的"),("plausibel","合理可信的"),("präzise","精準的"),
("problematisch","成問題的"),("prozessual","過程性的"),("reflektiert","經過反思的"),
("relevant","切題的"),("revidierbar","可修正的"),("schlüssig","嚴謹成立的"),
("spezifisch","特定的"),("stringent","嚴謹的"),("strukturell","結構性的"),
("substanziell","實質的"),("systematisch","系統的"),("theoretisch","理論的"),
("triftig","有力的"),("überzeugend","有說服力的"),("umfassend","全面的"),
("unhintergehbar","無法迴避的"),("unverzichtbar","不可或缺的"),("vielschichtig","多層次的"),
("wissenschaftlich","科學的"),("widersprüchlich","矛盾的"),("zielgerichtet","目標導向的"),
]

def build_level(level, nouns, verbs, adjs):
    out = []
    for row in nouns:
        out.append(entry(*row, level))
    for word, zh in verbs:
        out.append(entry(None, word, None, zh, "動詞", level))
    for word, zh in adjs:
        out.append(entry(None, word, None, zh, "形容詞", level))
    return out

def main():
    existing = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    # drop any previous B1/B2/C1 to allow re-run
    base = [w for w in existing if w.get("level") in ("A1", "A2")]
    seen = {(w["word"].lower(), w["level"], w.get("article")) for w in base}

    added = []
    for chunk in [
        build_level("B1", B1_NOUNS, B1_VERBS, B1_ADJ),
        build_level("B2", B2_NOUNS, B2_VERBS, B2_ADJ),
        build_level("C1", C1_NOUNS, C1_VERBS, C1_ADJ),
    ]:
        for w in chunk:
            key = (w["word"].lower(), w["level"], w.get("article"))
            if key in seen:
                continue
            # unique id
            wid = w["id"]
            n = 2
            ids = {x["id"] for x in base} | {x["id"] for x in added}
            while wid in ids:
                wid = f"{w['id']}_{n}"
                n += 1
            w["id"] = wid
            seen.add(key)
            added.append(w)

    merged = base + added
    counts = {}
    for w in merged:
        counts[w["level"]] = counts.get(w["level"], 0) + 1
    JSON_PATH.write_text(json.dumps(merged, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print("counts", counts, "total", len(merged), "added", len(added))

if __name__ == "__main__":
    main()
