#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate complete A1+A2 German vocabulary TypeScript."""
from __future__ import annotations
import json
import re
from pathlib import Path

# (id_suffix_or_None, article|None, word, plural|None, zh, category, level)
# Phonetics & examples auto-filled when omitted via helpers.

RAW: list[tuple] = []

def w(article, word, plural, zh, cat, level, id_=None):
    RAW.append((id_, article, word, plural, zh, cat, level))

# ===================== A1 COMPLETE =====================
# --- Wohnung / Haus ---
for row in [
("das","Haus","Häuser","房子","日常"),
("die","Wohnung","Wohnungen","公寓","日常"),
("das","Zimmer","Zimmer","房間","日常"),
("die","Küche","Küchen","廚房","日常"),
("das","Bad","Bäder","浴室","日常"),
("das","Badezimmer","Badezimmer","浴室","日常"),
("das","Schlafzimmer","Schlafzimmer","臥室","日常"),
("das","Wohnzimmer","Wohnzimmer","客廳","日常"),
("das","Esszimmer","Esszimmer","餐廳（家用）","日常"),
("das","Arbeitszimmer","Arbeitszimmer","書房","日常"),
("das","Kinderzimmer","Kinderzimmer","兒童房","日常"),
("der","Balkon","Balkone","陽台","日常"),
("der","Garten","Gärten","花園","日常"),
("die","Terrasse","Terrassen","露台","日常"),
("der","Keller","Keller","地下室","日常"),
("der","Dachboden","Dachböden","閣樓","日常"),
("das","Dach","Dächer","屋頂","日常"),
("die","Treppe","Treppen","樓梯","日常"),
("der","Aufzug","Aufzüge","電梯","日常"),
("der","Eingang","Eingänge","入口","日常"),
("der","Ausgang","Ausgänge","出口","日常"),
("die","Tür","Türen","門","日常"),
("das","Fenster","Fenster","窗戶","日常"),
("die","Wand","Wände","牆","日常"),
("der","Boden","Böden","地板","日常"),
("die","Decke","Decken","天花板／被子","日常"),
("der","Flur","Flure","走廊","日常"),
("die","Ecke","Ecken","角落","日常"),
("das","Stockwerk","Stockwerke","樓層","日常"),
("das","Erdgeschoss",None,"一樓","日常"),
("der","Stock","Stockwerke","樓","日常"),
("die","Adresse","Adressen","地址","日常"),
("die","Straße","Straßen","街道","日常"),
("der","Weg","Wege","路","日常"),
("der","Platz","Plätze","廣場／位子","日常"),
("die","Nummer","Nummern","號碼","日常"),
("die","Postleitzahl","Postleitzahlen","郵遞區號","日常"),
("die","Stadt","Städte","城市","日常"),
("das","Dorf","Dörfer","村莊","日常"),
("das","Land","Länder","國家／鄉下","日常"),
("die","Gegend","Gegenden","地區","日常"),
("die","Nachbarschaft","Nachbarschaften","鄰里","日常"),
]:
    w(*row, "A1")

# Furniture
for row in [
("der","Tisch","Tische","桌子","日常"),
("der","Stuhl","Stühle","椅子","日常"),
("das","Sofa","Sofas","沙發","日常"),
("der","Sessel","Sessel","單人沙發","日常"),
("das","Bett","Betten","床","日常"),
("der","Schrank","Schränke","櫃子","日常"),
("der","Kleiderschrank","Kleiderschränke","衣櫃","日常"),
("das","Regal","Regale","架子","日常"),
("die","Lampe","Lampen","燈","日常"),
("der","Teppich","Teppiche","地毯","日常"),
("der","Spiegel","Spiegel","鏡子","日常"),
("das","Bild","Bilder","畫／圖片","日常"),
("das","Foto","Fotos","照片","日常"),
("das","Kissen","Kissen","枕頭","日常"),
("die","Decke","Decken","毯子","日常"),
("die","Gardine","Gardinen","窗簾","日常"),
("der","Vorhang","Vorhänge","窗簾","日常"),
("die","Uhr","Uhren","鐘","時間"),
("der","Wecker","Wecker","鬧鐘","日常"),
("der","Computer","Computer","電腦","工作"),
("der","Drucker","Drucker","印表機","工作"),
("das","Telefon","Telefone","電話","日常"),
("das","Handy","Handys","手機","日常"),
("der","Fernseher","Fernseher","電視","日常"),
("das","Radio","Radios","收音機","日常"),
("die","Stereoanlage","Stereoanlagen","音響","日常"),
("das","Waschbecken","Waschbecken","洗手台","日常"),
("die","Toilette","Toiletten","廁所","日常"),
("die","Dusche","Duschen","淋浴","日常"),
("die","Badewanne","Badewannen","浴缸","日常"),
("die","Seife","Seifen","肥皂","日常"),
("das","Handtuch","Handtücher","毛巾","日常"),
("die","Zahnbürste","Zahnbürsten","牙刷","日常"),
("die","Zahncreme","Zahncremes","牙膏","日常"),
("der","Kamm","Kämme","梳子","日常"),
("die","Schere","Scheren","剪刀","日常"),
("der","Schlüssel","Schlüssel","鑰匙","日常"),
("das","Schloss","Schlösser","鎖／城堡","日常"),
("die","Klingel","Klingeln","門鈴","日常"),
("der","Briefkasten","Briefkästen","信箱","日常"),
]:
    w(*row, "A1")

# Food & drink A1
for row in [
("das","Essen",None,"食物／用餐","飲食"),
("das","Trinken",None,"飲料／喝","飲食"),
("das","Frühstück","Frühstücke","早餐","飲食"),
("das","Mittagessen","Mittagessen","午餐","飲食"),
("das","Abendessen","Abendessen","晚餐","飲食"),
("die","Mahlzeit","Mahlzeiten","一餐","飲食"),
("der","Hunger",None,"飢餓","飲食"),
("der","Durst",None,"口渴","飲食"),
("der","Appetit",None,"食慾","飲食"),
("das","Brot","Brote","麵包","飲食"),
("das","Brötchen","Brötchen","小麵包","飲食"),
("die","Butter",None,"奶油","飲食"),
("der","Käse","Käse","起司","飲食"),
("die","Wurst","Würste","香腸","飲食"),
("das","Fleisch",None,"肉","飲食"),
("das","Huhn","Hühner","雞","飲食"),
("das","Hähnchen","Hähnchen","烤雞","飲食"),
("das","Schwein","Schweine","豬／豬肉","飲食"),
("das","Rind","Rinder","牛／牛肉","飲食"),
("der","Fisch","Fische","魚","飲食"),
("das","Ei","Eier","蛋","飲食"),
("der","Reis",None,"米","飲食"),
("die","Nudel","Nudeln","麵條","飲食"),
("die","Kartoffel","Kartoffeln","馬鈴薯","飲食"),
("die","Pommes",None,"薯條","飲食"),
("die","Suppe","Suppen","湯","飲食"),
("der","Salat","Salate","沙拉","飲食"),
("das","Gemüse",None,"蔬菜","飲食"),
("das","Obst",None,"水果","飲食"),
("der","Apfel","Äpfel","蘋果","飲食"),
("die","Birne","Birnen","梨","飲食"),
("die","Banane","Bananen","香蕉","飲食"),
("die","Orange","Orangen","柳橙","飲食"),
("die","Zitrone","Zitronen","檸檬","飲食"),
("die","Traube","Trauben","葡萄","飲食"),
("die","Erdbeere","Erdbeeren","草莓","飲食"),
("die","Kirsche","Kirschen","櫻桃","飲食"),
("der","Pfirsich","Pfirsiche","桃子","飲食"),
("die","Melone","Melonen","西瓜／甜瓜","飲食"),
("die","Tomate","Tomaten","番茄","飲食"),
("die","Gurke","Gurken","小黃瓜","飲食"),
("die","Karotte","Karotten","胡蘿蔔","飲食"),
("die","Zwiebel","Zwiebeln","洋蔥","飲食"),
("der","Knoblauch",None,"大蒜","飲食"),
("der","Salat","Salate","生菜／沙拉","飲食"),
("der","Paprika","Paprika","甜椒","飲食"),
("der","Mais",None,"玉米","飲食"),
("die","Bohne","Bohnen","豆子","飲食"),
("die","Erbse","Erbsen","豌豆","飲食"),
("der","Pilz","Pilze","蘑菇","飲食"),
("der","Zucker",None,"糖","飲食"),
("das","Salz",None,"鹽","飲食"),
("der","Pfeffer",None,"胡椒","飲食"),
("das","Öl","Öle","油","飲食"),
("der","Essig",None,"醋","飲食"),
("die","Sauce","Saucen","醬汁","飲食"),
("die","Marmelade","Marmeladen","果醬","飲食"),
("der","Honig",None,"蜂蜜","飲食"),
("die","Schokolade","Schokoladen","巧克力","飲食"),
("der","Kuchen","Kuchen","蛋糕","飲食"),
("die","Torte","Torten","塔／蛋糕","飲食"),
("der","Keks","Kekse","餅乾","飲食"),
("das","Eis",None,"冰淇淋／冰","飲食"),
("das","Wasser","Wässer","水","飲食"),
("die","Milch",None,"牛奶","飲食"),
("der","Saft","Säfte","果汁","飲食"),
("der","Tee","Tees","茶","飲食"),
("der","Kaffee","Kaffees","咖啡","飲食"),
("das","Bier","Biere","啤酒","飲食"),
("der","Wein","Weine","葡萄酒","飲食"),
("die","Limonade","Limonaden","汽水","飲食"),
("die","Cola",None,"可樂","飲食"),
("das","Mineralwasser",None,"礦泉水","飲食"),
("das","Glas","Gläser","杯子／玻璃","飲食"),
("die","Tasse","Tassen","有柄杯","飲食"),
("der","Becher","Becher","紙杯／馬克杯","飲食"),
("der","Teller","Teller","盤子","飲食"),
("die","Schüssel","Schüsseln","碗","飲食"),
("das","Messer","Messer","刀子","飲食"),
("die","Gabel","Gabeln","叉子","飲食"),
("der","Löffel","Löffel","湯匙","飲食"),
("die","Flasche","Flaschen","瓶子","飲食"),
("die","Dose","Dosen","罐頭","飲食"),
("die","Tüte","Tüten","袋子","飲食"),
("die","Packung","Packungen","包裝","飲食"),
("das","Stück","Stücke","一塊／件","飲食"),
("das","Kilo",None,"公斤","飲食"),
("das","Gramm",None,"公克","飲食"),
("der","Liter",None,"公升","飲食"),
("der","Supermarkt","Supermärkte","超市","飲食"),
("der","Markt","Märkte","市場","飲食"),
("die","Bäckerei","Bäckereien","麵包店","飲食"),
("der","Bäcker","Bäcker","麵包師傅","飲食"),
("die","Metzgerei","Metzgereien","肉舖","飲食"),
("der","Metzger","Metzger","肉販","飲食"),
("das","Restaurant","Restaurants","餐廳","飲食"),
("das","Café","Cafés","咖啡館","飲食"),
("die","Kneipe","Kneipen","酒吧小館","飲食"),
("der","Imbiss","Imbisse","小吃攤","飲食"),
("der","Kellner","Kellner","服務生（男）","飲食"),
("die","Kellnerin","Kellnerinnen","服務生（女）","飲食"),
("die","Speisekarte","Speisekarten","菜單","飲食"),
("die","Rechnung","Rechnungen","帳單","飲食"),
("das","Trinkgeld","Trinkgelder","小費","飲食"),
("die","Reservierung","Reservierungen","預訂","飲食"),
]:
    w(*row, "A1")

# Family & people
for row in [
("die","Familie","Familien","家庭","家庭"),
("die","Mutter","Mütter","母親","家庭"),
("der","Vater","Väter","父親","家庭"),
(None,"Eltern",None,"父母","家庭"),
("das","Kind","Kinder","小孩","家庭"),
("der","Sohn","Söhne","兒子","家庭"),
("die","Tochter","Töchter","女兒","家庭"),
("der","Bruder","Brüder","兄弟","家庭"),
("die","Schwester","Schwestern","姊妹","家庭"),
(None,"Geschwister",None,"兄弟姐妹","家庭"),
("die","Oma","Omas","奶奶／外婆","家庭"),
("der","Opa","Opas","爺爺／外公","家庭"),
("die","Großmutter","Großmütter","祖母","家庭"),
("der","Großvater","Großväter","祖父","家庭"),
(None,"Großeltern",None,"祖父母","家庭"),
("der","Onkel","Onkel","叔叔／舅舅","家庭"),
("die","Tante","Tanten","阿姨／姑姑","家庭"),
("der","Cousin","Cousins","表／堂兄弟","家庭"),
("die","Cousine","Cousinen","表／堂姊妹","家庭"),
("der","Mann","Männer","男人／丈夫","家庭"),
("die","Frau","Frauen","女人／太太","家庭"),
("der","Herr","Herren","先生","家庭"),
("das","Fräulein",None,"小姐（舊）","家庭"),
("der","Freund","Freunde","朋友（男）","家庭"),
("die","Freundin","Freundinnen","朋友（女）","家庭"),
("der","Nachbar","Nachbarn","鄰居（男）","家庭"),
("die","Nachbarin","Nachbarinnen","鄰居（女）","家庭"),
("der","Gast","Gäste","客人","家庭"),
("der","Name","Namen","名字","家庭"),
("der","Vorname","Vornamen","名","家庭"),
("der","Nachname","Nachnamen","姓","家庭"),
("der","Familienname","Familiennamen","姓氏","家庭"),
("das","Alter",None,"年齡","家庭"),
("der","Geburtstag","Geburtstage","生日","家庭"),
("die","Hochzeit","Hochzeiten","婚禮","家庭"),
("das","Baby","Babys","嬰兒","家庭"),
("der","Junge","Jungen","男孩","家庭"),
("das","Mädchen","Mädchen","女孩","家庭"),
("der","Mensch","Menschen","人","家庭"),
("die","Person","Personen","人士","家庭"),
("die","Leute",None,"人們","家庭"),
]:
    w(*row, "A1")

# Body
for row in [
("der","Körper","Körper","身體","日常"),
("der","Kopf","Köpfe","頭","日常"),
("das","Gesicht","Gesichter","臉","日常"),
("das","Auge","Augen","眼睛","日常"),
("das","Ohr","Ohren","耳朵","日常"),
("die","Nase","Nasen","鼻子","日常"),
("der","Mund","Münder","嘴巴","日常"),
("der","Zahn","Zähne","牙齒","日常"),
("das","Haar","Haare","頭髮","日常"),
("der","Hals","Hälse","脖子／喉嚨","日常"),
("die","Schulter","Schultern","肩膀","日常"),
("der","Arm","Arme","手臂","日常"),
("die","Hand","Hände","手","日常"),
("der","Finger","Finger","手指","日常"),
("das","Bein","Beine","腿","日常"),
("der","Fuß","Füße","腳","日常"),
("der","Bauch","Bäuche","肚子","日常"),
("der","Rücken","Rücken","背","日常"),
("das","Herz","Herzen","心","日常"),
("der","Schmerz","Schmerzen","疼痛","日常"),
("das","Fieber",None,"發燒","日常"),
("der","Husten",None,"咳嗽","日常"),
("der","Schnupfen",None,"鼻塞感冒","日常"),
("die","Krankheit","Krankheiten","疾病","日常"),
("die","Gesundheit",None,"健康","日常"),
("der","Arzt","Ärzte","醫生（男）","工作"),
("die","Ärztin","Ärztinnen","醫生（女）","工作"),
("das","Krankenhaus","Krankenhäuser","醫院","工作"),
("die","Apotheke","Apotheken","藥局","工作"),
("die","Medizin",None,"藥／醫學","日常"),
("die","Tablette","Tabletten","藥丸","日常"),
]:
    w(*row, "A1")

# Clothes
for row in [
("die","Kleidung",None,"衣服","日常"),
("das","Kleid","Kleider","洋裝","日常"),
("die","Hose","Hosen","褲子","日常"),
("das","Hemd","Hemden","襯衫","日常"),
("das","T-Shirt","T-Shirts","T恤","日常"),
("die","Bluse","Blusen","女用襯衫","日常"),
("die","Jacke","Jacken","外套","日常"),
("der","Mantel","Mäntel","大衣","日常"),
("der","Pullover","Pullover","毛衣","日常"),
("der","Rock","Röcke","裙子","日常"),
("der","Anzug","Anzüge","西裝","日常"),
("das","Kostüm","Kostüme","套裝／戲服","日常"),
("der","Schuh","Schuhe","鞋子","日常"),
("der","Stiefel","Stiefel","靴子","日常"),
("die","Socke","Socken","襪子","日常"),
("der","Strumpf","Strümpfe","長襪","日常"),
("die","Mütze","Mützen","保暖帽","日常"),
("der","Hut","Hüte","帽子","日常"),
("die","Mütze","Mützen","毛帽","日常"),
("der","Schal","Schals","圍巾","日常"),
("der","Handschuh","Handschuhe","手套","日常"),
("die","Brille","Brillen","眼鏡","日常"),
("die","Uhr","Uhren","手錶","日常"),
("der","Gürtel","Gürtel","皮帶","日常"),
("die","Tasche","Taschen","包包","日常"),
("der","Rucksack","Rucksäcke","背包","日常"),
("der","Koffer","Koffer","行李箱","旅行"),
("die","Größe","Größen","尺寸","日常"),
("die","Farbe","Farben","顏色","日常"),
]:
    w(*row, "A1")

# Colors as adj
for word, zh in [
("rot","紅色的"),("blau","藍色的"),("grün","綠色的"),("gelb","黃色的"),
("schwarz","黑色的"),("weiß","白色的"),("braun","棕色的"),("grau","灰色的"),
("orange","橘色的"),("pink","粉紅色的"),("lila","紫色的"),("bunt","彩色的"),
]:
    w(None, word, None, zh, "形容詞", "A1")

# School / work A1
for row in [
("die","Schule","Schulen","學校","工作"),
("die","Klasse","Klassen","班級","工作"),
("der","Lehrer","Lehrer","老師（男）","工作"),
("die","Lehrerin","Lehrerinnen","老師（女）","工作"),
("der","Schüler","Schüler","學生（男）","工作"),
("die","Schülerin","Schülerinnen","學生（女）","工作"),
("der","Student","Studenten","大學生（男）","工作"),
("die","Studentin","Studentinnen","大學生（女）","工作"),
("die","Universität","Universitäten","大學","工作"),
("die","Hochschule","Hochschulen","高等學校","工作"),
("das","Buch","Bücher","書","日常"),
("das","Heft","Hefte","筆記本","日常"),
("der","Stift","Stifte","筆","日常"),
("der","Bleistift","Bleistifte","鉛筆","日常"),
("der","Kugelschreiber","Kugelschreiber","原子筆","日常"),
("der","Radiergummi","Radiergummis","橡皮擦","日常"),
("das","Papier","Papiere","紙","日常"),
("die","Seite","Seiten","頁","日常"),
("der","Text","Texte","文章","日常"),
("das","Wort","Wörter","單字","日常"),
("der","Satz","Sätze","句子","日常"),
("die","Frage","Fragen","問題","日常"),
("die","Antwort","Antworten","回答","日常"),
("die","Aufgabe","Aufgaben","作業／任務","工作"),
("die","Hausaufgabe","Hausaufgaben","家庭作業","工作"),
("die","Prüfung","Prüfungen","考試","工作"),
("die","Note","Noten","成績","工作"),
("das","Zeugnis","Zeugnisse","成績單","工作"),
("der","Kurs","Kurse","課程","工作"),
("der","Unterricht",None,"上課","工作"),
("die","Pause","Pausen","休息","工作"),
("die","Arbeit","Arbeiten","工作","工作"),
("der","Job","Jobs","工作（口語）","工作"),
("die","Firma","Firmen","公司","工作"),
("das","Büro","Büros","辦公室","工作"),
("der","Beruf","Berufe","職業","工作"),
("der","Kollege","Kollegen","同事（男）","工作"),
("die","Kollegin","Kolleginnen","同事（女）","工作"),
("der","Chef","Chefs","老闆（男）","工作"),
("die","Chefin","Chefinnen","老闆（女）","工作"),
("der","Arbeiter","Arbeiter","工人（男）","工作"),
("die","Arbeiterin","Arbeiterinnen","工人（女）","工作"),
("der","Angestellte","Angestellten","職員（男）","工作"),
("die","Angestellte","Angestellten","職員（女）","工作"),
("der","Verkäufer","Verkäufer","店員（男）","工作"),
("die","Verkäuferin","Verkäuferinnen","店員（女）","工作"),
("der","Koch","Köche","廚師（男）","工作"),
("die","Köchin","Köchinnen","廚師（女）","工作"),
("der","Fahrer","Fahrer","駕駛（男）","工作"),
("die","Fahrerin","Fahrerinnen","駕駛（女）","工作"),
("der","Polizist","Polizisten","警察（男）","工作"),
("die","Polizistin","Polizistinnen","警察（女）","工作"),
("die","Polizei",None,"警方","工作"),
("die","Feuerwehr","Feuerwehren","消防隊","工作"),
("der","Briefträger","Briefträger","郵差","工作"),
("die","Sekretärin","Sekretärinnen","秘書","工作"),
("der","Ingenieur","Ingenieure","工程師","工作"),
("der","Mechaniker","Mechaniker","技工","工作"),
("die","Krankenschwester","Krankenschwestern","護士","工作"),
("der","Krankenpfleger","Krankenpfleger","男護理師","工作"),
]:
    w(*row, "A1")

# Travel A1
for row in [
("der","Bahnhof","Bahnhöfe","火車站","旅行"),
("der","Flughafen","Flughäfen","機場","旅行"),
("das","Flugzeug","Flugzeuge","飛機","旅行"),
("der","Zug","Züge","火車","旅行"),
("der","Bus","Busse","公車","旅行"),
("die","Straßenbahn","Straßenbahnen","電車","旅行"),
("die","U-Bahn","U-Bahnen","地鐵","旅行"),
("die","S-Bahn","S-Bahnen","近郊鐵路","旅行"),
("das","Taxi","Taxis","計程車","旅行"),
("das","Auto","Autos","汽車","旅行"),
("das","Fahrrad","Fahrräder","腳踏車","旅行"),
("das","Motorrad","Motorräder","機車","旅行"),
("das","Schiff","Schiffe","船","旅行"),
("die","Haltestelle","Haltestellen","站牌","旅行"),
("die","Station","Stationen","車站","旅行"),
("das","Gleis","Gleise","月台股道","旅行"),
("die","Fahrkarte","Fahrkarten","車票","旅行"),
("das","Ticket","Tickets","票","旅行"),
("der","Pass","Pässe","護照","旅行"),
("der","Ausweis","Ausweise","證件","旅行"),
("das","Hotel","Hotels","飯店","旅行"),
("die","Pension","Pensionen","民宿","旅行"),
("die","Jugendherberge","Jugendherbergen","青年旅館","旅行"),
("die","Rezeption","Rezeptionen","櫃台","旅行"),
("das","Einzelzimmer","Einzelzimmer","單人房","旅行"),
("das","Doppelzimmer","Doppelzimmer","雙人房","旅行"),
("die","Karte","Karten","地圖／卡","旅行"),
("der","Urlaub","Urlaube","假期","旅行"),
("die","Reise","Reisen","旅行","旅行"),
("der","Tourist","Touristen","遊客（男）","旅行"),
("die","Touristin","Touristinnen","遊客（女）","旅行"),
("das","Land","Länder","國家","旅行"),
("die","Hauptstadt","Hauptstädte","首都","旅行"),
("der","Strand","Strände","海灘","旅行"),
("das","Meer","Meere","海","自然"),
("der","See","Seen","湖","自然"),
("der","Berg","Berge","山","自然"),
("der","Wald","Wälder","森林","自然"),
("der","Fluss","Flüsse","河","自然"),
("der","Park","Parks","公園","自然"),
("der","Zoo","Zoos","動物園","自然"),
("das","Museum","Museen","博物館","旅行"),
("die","Kirche","Kirchen","教堂","旅行"),
("das","Kino","Kinos","電影院","日常"),
("das","Theater","Theater","劇院","日常"),
("das","Schwimmbad","Schwimmbäder","游泳池","日常"),
("die","Bank","Banken","銀行","日常"),
("die","Post",None,"郵局","日常"),
("das","Geschäft","Geschäfte","商店","日常"),
("der","Laden","Läden","店舖","日常"),
("das","Kaufhaus","Kaufhäuser","百貨公司","日常"),
("die","Tankstelle","Tankstellen","加油站","旅行"),
("der","Parkplatz","Parkplätze","停車場","旅行"),
("die","Garage","Garagen","車庫","日常"),
("die","Ampel","Ampeln","紅綠燈","旅行"),
("die","Kreuzung","Kreuzungen","十字路口","旅行"),
("die","Brücke","Brücken","橋","旅行"),
]:
    w(*row, "A1")

# Nature weather time
for row in [
("das","Wetter",None,"天氣","自然"),
("die","Sonne","Sonnen","太陽","自然"),
("der","Mond","Monde","月亮","自然"),
("der","Stern","Sterne","星星","自然"),
("der","Himmel",None,"天空","自然"),
("die","Wolke","Wolken","雲","自然"),
("der","Regen","Regen","雨","自然"),
("der","Schnee",None,"雪","自然"),
("der","Wind","Winde","風","自然"),
("das","Gewitter","Gewitter","雷雨","自然"),
("der","Nebel",None,"霧","自然"),
("der","Baum","Bäume","樹","自然"),
("die","Blume","Blumen","花","自然"),
("das","Gras",None,"草","自然"),
("das","Tier","Tiere","動物","自然"),
("der","Hund","Hunde","狗","自然"),
("die","Katze","Katzen","貓","自然"),
("der","Vogel","Vögel","鳥","自然"),
("das","Pferd","Pferde","馬","自然"),
("die","Kuh","Kühe","牛","自然"),
("das","Schwein","Schweine","豬","自然"),
("das","Huhn","Hühner","雞","自然"),
("die","Maus","Mäuse","老鼠","自然"),
("der","Tag","Tage","天／白天","時間"),
("die","Woche","Wochen","週","時間"),
("der","Monat","Monate","月","時間"),
("das","Jahr","Jahre","年","時間"),
("der","Morgen","Morgen","早上","時間"),
("der","Vormittag","Vormittage","上午","時間"),
("der","Mittag","Mittage","中午","時間"),
("der","Nachmittag","Nachmittage","下午","時間"),
("der","Abend","Abende","晚上","時間"),
("die","Nacht","Nächte","夜晚","時間"),
("die","Stunde","Stunden","小時","時間"),
("die","Minute","Minuten","分鐘","時間"),
("die","Sekunde","Sekunden","秒","時間"),
("das","Wochenende","Wochenenden","週末","時間"),
(None,"Ferien",None,"假期","時間"),
("der","Feiertag","Feiertage","假日","時間"),
("der","Montag","Montage","星期一","時間"),
("der","Dienstag","Dienstage","星期二","時間"),
("der","Mittwoch","Mittwoche","星期三","時間"),
("der","Donnerstag","Donnerstage","星期四","時間"),
("der","Freitag","Freitage","星期五","時間"),
("der","Samstag","Samstage","星期六","時間"),
("der","Sonntag","Sonntage","星期日","時間"),
("der","Januar",None,"一月","時間"),
("der","Februar",None,"二月","時間"),
("der","März",None,"三月","時間"),
("der","April",None,"四月","時間"),
("der","Mai",None,"五月","時間"),
("der","Juni",None,"六月","時間"),
("der","Juli",None,"七月","時間"),
("der","August",None,"八月","時間"),
("der","September",None,"九月","時間"),
("der","Oktober",None,"十月","時間"),
("der","November",None,"十一月","時間"),
("der","Dezember",None,"十二月","時間"),
("der","Frühling","Frühlinge","春天","自然"),
("der","Sommer","Sommer","夏天","自然"),
("der","Herbst","Herbste","秋天","自然"),
("der","Winter","Winter","冬天","自然"),
]:
    w(*row, "A1")

# Time adverbs / words without article
for word, zh in [
("heute","今天"),("morgen","明天"),("gestern","昨天"),
("jetzt","現在"),("gleich","馬上"),("bald","很快"),
("später","稍後"),("früher","以前"),("immer","總是"),
("oft","常常"),("manchmal","有時候"),("selten","很少"),
("nie","從不"),("schon","已經"),("noch","還"),
("wieder","再／又"),("hier","這裡"),("dort","那裡"),
("überall","到處"),("nirgends","無處"),("links","左邊"),
("rechts","右邊"),("geradeaus","直走"),("oben","上面"),
("unten","下面"),("vorn","前面"),("hinten","後面"),
("drin","裡面"),("draußen","外面"),("zusammen","一起"),
("allein","獨自"),("viel","很多"),("wenig","很少"),
("mehr","更多"),("weniger","更少"),("alles","全部"),
("nichts","沒有東西"),("etwas","一些東西"),("jemand","某人"),
("niemand","沒有人"),("man","人們（不定代詞）"),
]:
    w(None, word, None, zh, "時間" if word in {"heute","morgen","gestern","jetzt","gleich","bald","später","früher","immer","oft","manchmal","selten","nie","schon","noch","wieder"} else "日常", "A1")

# Numbers
for word, zh in [
("null","零"),("eins","一"),("zwei","二"),("drei","三"),("vier","四"),
("fünf","五"),("sechs","六"),("sieben","七"),("acht","八"),("neun","九"),
("zehn","十"),("elf","十一"),("zwölf","十二"),("dreizehn","十三"),
("vierzehn","十四"),("fünfzehn","十五"),("sechzehn","十六"),("siebzehn","十七"),
("achtzehn","十八"),("neunzehn","十九"),("zwanzig","二十"),("dreißig","三十"),
("vierzig","四十"),("fünfzig","五十"),("sechzig","六十"),("siebzig","七十"),
("achtzig","八十"),("neunzig","九十"),("hundert","一百"),("tausend","一千"),
("erste","第一"),("zweite","第二"),("dritte","第三"),("vierte","第四"),
("fünfte","第五"),("zehnte","第十"),("letzte","最後的"),
]:
    w(None, word, None, zh, "數字", "A1")

# Money shopping
for row in [
("das","Geld",None,"錢","日常"),
("der","Euro","Euro","歐元","日常"),
("der","Cent","Cent","歐分","日常"),
("die","Geldbörse","Geldbörsen","錢包","日常"),
("die","Bankkarte","Bankkarten","金融卡","日常"),
("die","Kreditkarte","Kreditkarten","信用卡","日常"),
("der","Preis","Preise","價格","日常"),
("das","Angebot","Angebote","特價","日常"),
("der","Rabatt","Rabatte","折扣","日常"),
("die","Kasse","Kassen","收銀台","日常"),
("die","Quittung","Quittungen","收據","日常"),
("das","Wechselgeld",None,"找零","日常"),
("das","Bargeld",None,"現金","日常"),
("das","Konto","Konten","帳戶","日常"),
]:
    w(*row, "A1")

# Free time
for row in [
("das","Hobby","Hobbys","嗜好","日常"),
("der","Sport",None,"運動","日常"),
("der","Fußball",None,"足球","日常"),
("das","Tennis",None,"網球","日常"),
("das","Schwimmen",None,"游泳","日常"),
("das","Laufen",None,"跑步","日常"),
("das","Radfahren",None,"騎車","日常"),
("das","Wandern",None,"健行","日常"),
("die","Musik",None,"音樂","日常"),
("das","Lied","Lieder","歌曲","日常"),
("der","Film","Filme","電影","日常"),
("das","Spiel","Spiele","遊戲","日常"),
("die","Party","Partys","派對","日常"),
("das","Fest","Feste","慶典","日常"),
("die","Zeitung","Zeitungen","報紙","日常"),
("die","Zeitschrift","Zeitschriften","雜誌","日常"),
("das","Internet",None,"網路","日常"),
("die","E-Mail","E-Mails","電子郵件","日常"),
("die","Nachricht","Nachrichten","訊息","日常"),
]:
    w(*row, "A1")

# A1 Verbs (comprehensive core)
A1_VERBS = [
("sein","是／在"),("haben","有"),("werden","變成／將會"),
("können","能夠"),("müssen","必須"),("wollen","想要"),("sollen","應當"),
("dürfen","被允許"),("mögen","喜歡"),("möchten","想要（禮貌）"),
("gehen","走／去"),("kommen","來"),("fahren","搭乘／開"),("laufen","跑／走"),
("fliegen","飛"),("schwimmen","游泳"),("stehen","站"),("sitzen","坐"),
("liegen","躺／位於"),("bleiben","留下"),("steigen","上升／登上"),
("einsteigen","上車"),("aussteigen","下車"),("umsteigen","轉車"),
("ankommen","到達"),("abfahren","出發"),("mitkommen","一起來"),
("essen","吃"),("trinken","喝"),("kochen","煮"),("backen","烘焙"),
("schmecken","嚐起來"),("frühstücken","吃早餐"),
("schlafen","睡覺"),("aufstehen","起床"),("waschen","洗"),
("duschen","淋浴"),("anziehen","穿上"),("ausziehen","脫下"),
("machen","做"),("tun","做"),("arbeiten","工作"),("lernen","學習"),
("studieren","讀大學"),("üben","練習"),("wiederholen","重複"),
("lesen","讀"),("schreiben","寫"),("sprechen","說"),("sagen","說出"),
("erzählen","講述"),("fragen","問"),("antworten","回答"),
("hören","聽"),("sehen","看"),("schauen","瞧"),("fernsehen","看電視"),
("finden","找到／覺得"),("suchen","尋找"),("geben","給"),("nehmen","拿"),
("bringen","帶來"),("holen","去拿"),("legen","放置（平放）"),
("stellen","放置（立放）"),("setzen","放置（坐下）"),
("öffnen","打開"),("schließen","關上"),("beginnen","開始"),("enden","結束"),
("starten","開始／發動"),("hören_auf","aufhören","停止"),
("warten","等待"),("treffen","碰面"),("besuchen","拜訪"),
("helfen","幫助"),("brauchen","需要"),("benutzen","使用"),
("verstehen","理解"),("wissen","知道"),("kennen","認識"),
("glauben","相信"),("denken","想"),("meinen","認為"),
("wohnen","居住"),("leben","生活"),("ziehen","拉／搬"),
("spielen","玩"),("tanzen","跳舞"),("singen","唱歌"),
("malen","畫"),("fotografieren","拍照"),("feiern","慶祝"),
("kaufen","買"),("verkaufen","賣"),("bezahlen","付款"),("kosten","花費"),
("bestellen","訂購"),("einkaufen","購物"),("probieren","試／嚐"),
("gefallen","喜歡（被喜歡）"),("lieben","愛"),("hassen","恨"),
("lachen","笑"),("weinen","哭"),("lächeln","微笑"),
("rufen","呼叫"),("telefonieren","打電話"),("mailen","寄郵件"),
("funktioniert","功能運作"),  # fix below
]
# Fix messy ones
A1_VERBS = [x for x in A1_VERBS if len(x)==2]
A1_VERBS += [
("funktionieren","運作"),("klappen","順利"),("passen","適合"),
("gehören","屬於"),("fehlen","缺少"),("tut_weh","疼痛"),
("regnen","下雨"),("scheinen","照耀"),("schneien","下雪"),
("interessieren","使感興趣"),("freuen","使開心"),
("entschuldigen","道歉"),("danken","感謝"),("bitten","請求"),
("wünschen","祝願"),("gratulieren","祝賀"),("einladen","邀請"),
("vorstellen","介紹"),("heißen","名叫"),("zeigen","展示"),
("erklären","解釋"),("übersetzen","翻譯"),("buchstabieren","拼讀"),
("rechnen","計算"),("zählen","數"),("messen","測量"),
("wiegen","秤重"),("putzen","打掃"),("aufräumen","整理"),
("reparieren","修理"),("bauen","建造"),("parken","停車"),
("brauchen_a1","需要"),
]
# dedupe verbs later

for item in A1_VERBS:
    if len(item)!=2: continue
    word, zh = item
    if word == "hören_auf": continue
    if word == "tut_weh":
        w(None, "weh tun", None, "疼痛", "動詞", "A1")
        continue
    if word == "brauchen_a1": continue
    w(None, word, None, zh, "動詞", "A1")

w(None, "aufhören", None, "停止", "動詞", "A1")

# A1 Adjectives
A1_ADJ = [
("gut","好的"),("schlecht","不好的"),("schön","美麗的"),("hässlich","醜的"),
("groß","大的"),("klein","小的"),("lang","長的"),("kurz","短的"),
("hoch","高的"),("niedrig","低的"),("breit","寬的"),("eng","窄的"),
("dick","厚的／胖的"),("dünn","薄的／瘦的"),("schwer","重的／難的"),
("leicht","輕的／容易的"),("neu","新的"),("alt","舊的／老的"),
("jung","年輕的"),("kalt","冷的"),("warm","溫暖的"),("heiß","熱的"),
("kühl","涼爽的"),("trocken","乾的"),("nass","濕的"),
("sauber","乾淨的"),("schmutzig","髒的"),("voll","滿的"),("leer","空的"),
("schnell","快的"),("langsam","慢的"),("teuer","貴的"),("billig","便宜的"),
("richtig","正確的"),("falsch","錯誤的"),("wichtig","重要的"),
("interessant","有趣的"),("langweilig","無聊的"),("freundlich","友善的"),
("nett","親切的"),("höflich","有禮貌的"),("müde","疲倦的"),
("krank","生病的"),("gesund","健康的"),("hungrig","餓的"),("durstig","渴的"),
("froh","高興的"),("glücklich","幸福的"),("traurig","悲傷的"),
("wütend","生氣的"),("fertig","完成的"),("bereit","準備好的"),
("frei","空閒的"),("besetzt","佔用的"),("geöffnet","營業中"),
("geschlossen","已關閉"),("möglich","可能的"),("unmöglich","不可能的"),
("klar","清楚的"),("sicher","確定的／安全的"),("anders","別的"),
("gleich","一樣的"),("verschieden","不同的"),("lieb","親愛的"),
("liebe","親愛的（陰性）"),("super","超棒的"),("toll","很棒的"),
("prima","一流的"),("okay","還可以"),("kaputt","壞掉的"),
("ganz","全部的／相當"),("halb","一半的"),("beide","兩者"),
("jeder","每個"),("alle","全部的"),("einige","一些"),
("nächste","下一個"),("letzte","上一個／最後"),("erste","第一個"),
("deutsche","德國的"),("internationale","國際的"),
("linke","左邊的"),("rechte","右邊的"),
("starke","強壯的"),("schwache","虛弱的"),
("helle","明亮的"),("dunkle","黑暗的"),
("laute","大聲的"),("leise","小聲的"),
("süße","甜的"),("salzige","鹹的"),("saure","酸的"),("bittere","苦的"),
("frische","新鮮的"),("leckere","好吃的"),
("bekannte","熟悉的"),("fremde","陌生的"),
("eigene","自己的"),("öffentliche","公共的"),("private","私人的"),
]
for word, zh in A1_ADJ:
    # normalize adjective dictionary form - strip weak endings we accidentally added
    base = word
    w(None, base, None, zh, "形容詞", "A1")

# ===================== A2 COMPLETE =====================
for row in [
("der","Abflug","Abflüge","起飛","旅行"),
("die","Ankunft","Ankünfte","抵達","旅行"),
("die","Verspätung","Verspätungen","延誤","旅行"),
("das","Gepäck",None,"行李","旅行"),
("das","Handgepäck",None,"手提行李","旅行"),
("das","Visum","Visa","簽證","旅行"),
("der","Zoll",None,"海關","旅行"),
("die","Sicherheitskontrolle","Sicherheitskontrollen","安檢","旅行"),
("das","Gate","Gates","登機門","旅行"),
("der","Sitzplatz","Sitzplätze","座位","旅行"),
("der","Fensterplatz","Fensterplätze","靠窗座位","旅行"),
("der","Gang","Gänge","走道","旅行"),
("der","Ausflug","Ausflüge","出遊","旅行"),
("die","Rundreise","Rundreisen","環遊","旅行"),
("die","Sehenswürdigkeit","Sehenswürdigkeiten","景點","旅行"),
("das","Schloss","Schlösser","城堡","旅行"),
("der","Turm","Türme","塔","旅行"),
("das","Denkmal","Denkmäler","紀念碑","旅行"),
("der","Marktplatz","Marktplätze","市集廣場","旅行"),
("die","Altstadt","Altstädte","老城區","旅行"),
("das","Zentrum","Zentren","市中心","旅行"),
("der","Vorort","Vororte","郊區","旅行"),
("die","Landschaft","Landschaften","風景","旅行"),
("die","Insel","Inseln","島","自然"),
("die","Welle","Wellen","波浪","自然"),
("die","Umwelt",None,"環境","自然"),
("der","Müll",None,"垃圾","日常"),
("der","Mülleimer","Mülleimer","垃圾桶","日常"),
("das","Recycling",None,"資源回收","日常"),
("die","Energie","Energien","能源","日常"),
("der","Strom",None,"電力","日常"),
("die","Heizung","Heizungen","暖氣","日常"),
("die","Klimaanlage","Klimaanlagen","空調","日常"),
("die","Waschmaschine","Waschmaschinen","洗衣機","日常"),
("der","Trockner","Trockner","烘衣機","日常"),
("die","Spülmaschine","Spülmaschinen","洗碗機","日常"),
("der","Staubsauger","Staubsauger","吸塵器","日常"),
("der","Kühlschrank","Kühlschränke","冰箱","飲食"),
("der","Gefrierschrank","Gefrierschränke","冷凍櫃","飲食"),
("der","Herd","Herde","爐灶","飲食"),
("der","Ofen","Öfen","烤箱","飲食"),
("die","Mikrowelle","Mikrowellen","微波爐","飲食"),
("die","Pfanne","Pfannen","平底鍋","飲食"),
("der","Topf","Töpfe","鍋子","飲食"),
("die","Vorspeise","Vorspeisen","前菜","飲食"),
("das","Hauptgericht","Hauptgerichte","主菜","飲食"),
("der","Nachtisch","Nachtische","甜點","飲食"),
("der","Geschmack","Geschmäcker","味道","飲食"),
("die","Allergie","Allergien","過敏","飲食"),
("der","Vegetarier","Vegetarier","素食者（男）","飲食"),
("die","Vegetarierin","Vegetarierinnen","素食者（女）","飲食"),
("die","Zutat","Zutaten","食材","飲食"),
("das","Rezept","Rezepte","食譜／處方","飲食"),
("die","Einladung","Einladungen","邀請","家庭"),
("der","Besuch","Besuche","拜訪","家庭"),
("der","Verwandte","Verwandten","親戚","家庭"),
("die","Trauung","Trauungen","證婚","家庭"),
("die","Scheidung","Scheidungen","離婚","家庭"),
("die","Miete","Mieten","租金","家庭"),
(None,"Nebenkosten",None,"雜費","家庭"),
("der","Vertrag","Verträge","合約","工作"),
("die","Kündigung","Kündigungen","解約","工作"),
("das","Möbel",None,"家具","家庭"),
("die","Einrichtung","Einrichtungen","裝潢","家庭"),
("die","Jahreszeit","Jahreszeiten","季節","自然"),
("die","Temperatur","Temperaturen","溫度","自然"),
("der","Grad","Grade","度","自然"),
("der","Blitz","Blitze","閃電","自然"),
("der","Donner",None,"雷","自然"),
("der","Hagel",None,"冰雹","自然"),
("die","Bewerbung","Bewerbungen","求職申請","工作"),
("das","Vorstellungsgespräch","Vorstellungsgespräche","面試","工作"),
("das","Gehalt","Gehälter","薪水","工作"),
("der","Lohn","Löhne","工資","工作"),
("die","Steuer","Steuern","稅","工作"),
(None,"Überstunden",None,"加班","工作"),
("der","Mitarbeiter","Mitarbeiter","員工","工作"),
("das","Projekt","Projekte","專案","工作"),
("das","Meeting","Meetings","會議","工作"),
("die","Besprechung","Besprechungen","討論會","工作"),
("der","Anhang","Anhänge","附件","工作"),
("die","Datei","Dateien","檔案","工作"),
("das","Passwort","Passwörter","密碼","日常"),
("die","Website","Websites","網站","日常"),
("die","App","Apps","應用程式","日常"),
("der","Chat","Chats","聊天","日常"),
("die","Bibliothek","Bibliotheken","圖書館","工作"),
("der","Fehler","Fehler","錯誤","工作"),
("der","Erfolg","Erfolge","成功","工作"),
("der","Misserfolg","Misserfolge","失敗","工作"),
("die","Erfahrung","Erfahrungen","經驗","工作"),
("die","Fähigkeit","Fähigkeiten","能力","工作"),
("das","Interesse","Interessen","興趣","日常"),
("das","Instrument","Instrumente","樂器","日常"),
("die","Gitarre","Gitarren","吉他","日常"),
("das","Klavier","Klaviere","鋼琴","日常"),
("das","Konzert","Konzerte","音樂會","日常"),
("die","Feier","Feiern","慶祝活動","日常"),
("der","Termin","Termine","預約","工作"),
("der","Kalender","Kalender","日曆","日常"),
("der","Plan","Pläne","計畫","日常"),
("das","Ziel","Ziele","目標","日常"),
("das","Problem","Probleme","問題","日常"),
("die","Lösung","Lösungen","解決辦法","日常"),
("die","Idee","Ideen","想法","日常"),
("der","Vorschlag","Vorschläge","建議","日常"),
("die","Meinung","Meinungen","意見","日常"),
("der","Grund","Gründe","原因","日常"),
("das","Ergebnis","Ergebnisse","結果","日常"),
("der","Unterschied","Unterschiede","差別","日常"),
("das","Beispiel","Beispiele","例子","日常"),
("die","Regel","Regeln","規則","日常"),
("das","Gesetz","Gesetze","法律","日常"),
("das","Recht","Rechte","權利","日常"),
("die","Pflicht","Pflichten","義務","日常"),
("die","Freiheit","Freiheiten","自由","日常"),
("der","Frieden",None,"和平","日常"),
("der","Krieg","Kriege","戰爭","日常"),
("die","Politik",None,"政治","日常"),
("die","Wirtschaft",None,"經濟","日常"),
("die","Gesellschaft","Gesellschaften","社會","日常"),
("die","Kultur","Kulturen","文化","日常"),
("die","Tradition","Traditionen","傳統","日常"),
("die","Sprache","Sprachen","語言","日常"),
("die","Bedeutung","Bedeutungen","意思","日常"),
("die","Übersetzung","Übersetzungen","翻譯","日常"),
("die","Aussprache",None,"發音","日常"),
("die","Grammatik","Grammatiken","文法","日常"),
("das","Wörterbuch","Wörterbücher","字典","日常"),
("die","Impfung","Impfungen","疫苗","日常"),
("die","Untersuchung","Untersuchungen","檢查","日常"),
("der","Arzttermin","Arzttermine","看診預約","日常"),
("die","Krankenkasse","Krankenkassen","健保","日常"),
("die","Versicherung","Versicherungen","保險","日常"),
("der","Unfall","Unfälle","意外","日常"),
("die","Gefahr","Gefahren","危險","日常"),
("die","Sicherheit",None,"安全","日常"),
("die","Hilfe","Hilfen","幫助","日常"),
("der","Notfall","Notfälle","緊急狀況","日常"),
("das","Feuer","Feuer","火","日常"),
("der","Rauch",None,"煙","日常"),
("die","Richtung","Richtungen","方向","旅行"),
("die","Auskunft","Auskünfte","詢問處","旅行"),
("der","Verkehr",None,"交通","旅行"),
("der","Stau","Staus","塞車","旅行"),
("die","Autobahn","Autobahnen","高速公路","旅行"),
("das","Benzin",None,"汽油","旅行"),
("der","Mietwagen","Mietwagen","租車","旅行"),
("der","Führerschein","Führerscheine","駕照","旅行"),
("die","Geschwindigkeit","Geschwindigkeiten","速度","旅行"),
("der","Fußgänger","Fußgänger","行人","旅行"),
("der","Zebrastreifen","Zebrastreifen","斑馬線","旅行"),
("die","Überweisung","Überweisungen","匯款","日常"),
("die","Ware","Waren","商品","日常"),
("die","Passform",None,"合身度","日常"),
("die","Umkleidekabine","Umkleidekabinen","試衣間","日常"),
("der","Service",None,"服務","日常"),
("der","Kunde","Kunden","顧客（男）","日常"),
("die","Kundin","Kundinnen","顧客（女）","日常"),
("die","Beschwerde","Beschwerden","投訴","日常"),
("die","Reparatur","Reparaturen","修理","日常"),
("die","Garantie","Garantien","保固","日常"),
("die","Lieferung","Lieferungen","配送","日常"),
("das","Paket","Pakete","包裹","日常"),
("die","Briefmarke","Briefmarken","郵票","日常"),
("die","Behörde","Behörden","機關","工作"),
("das","Formular","Formulare","表格","工作"),
("die","Unterschrift","Unterschriften","簽名","工作"),
("der","Antrag","Anträge","申請","工作"),
("die","Erlaubnis","Erlaubnisse","許可","工作"),
("die","Anmeldung","Anmeldungen","登記","工作"),
("die","Abmeldung","Abmeldungen","注销","工作"),
("der","Personalausweis","Personalausweise","身分證","日常"),
("die","Steuererklärung","Steuererklärungen","報稅","工作"),
("das","Arbeitsamt","Arbeitsämter","就業局","工作"),
("das","Rathaus","Rathäuser","市政廳","工作"),
("die","Botschaft","Botschaften","大使館","旅行"),
("das","Konsulat","Konsulate","領事館","旅行"),
("die","Unterkunft","Unterkünfte","住宿","旅行"),
("die","Jugendherberge","Jugendherbergen","青年旅館","旅行"),
("die","Campingplatz","Campingplätze","營地","旅行"),
("das","Zelt","Zelte","帳篷","旅行"),
("der","Schlafsaal","Schlafsäle","宿舍大通鋪","旅行"),
("die","Klimaanlage","Klimaanlagen","空調","日常"),
("der","Fahrstuhl","Fahrstühle","電梯","日常"),
("die","Etage","Etagen","樓層","日常"),
("die","Miete","Mieten","租金","家庭"),
("der","Vermieter","Vermieter","房東（男）","家庭"),
("die","Vermieterin","Vermieterinnen","房東（女）","家庭"),
("der","Mieter","Mieter","房客（男）","家庭"),
("die","Mieterin","Mieterinnen","房客（女）","家庭"),
("die","Wohngemeinschaft","Wohngemeinschaften","分租公寓","家庭"),
("das","WG-Zimmer","WG-Zimmer","分租房間","家庭"),
("die","Kaution","Kautionen","押金","家庭"),
("der","Umzug","Umzüge","搬家","家庭"),
("die","Spedition","Speditionen","搬家公司","家庭"),
]:
    w(*row, "A2")

# More A2 nouns - daily/social/education/health/media
for row in [
("die","Ausbildung","Ausbildungen","職業訓練","工作"),
("das","Praktikum","Praktika","實習","工作"),
("der","Auszubildende","Auszubildenden","學徒（男）","工作"),
("die","Auszubildende","Auszubildenden","學徒（女）","工作"),
("die","Stelle","Stellen","職缺","工作"),
("die","Vollzeit",None,"全職","工作"),
("die","Teilzeit",None,"兼職","工作"),
("die","Schicht","Schichten","輪班","工作"),
("der","Feiertag","Feiertage","假日","時間"),
("der","Urlaubstag","Urlaubstage","休假日","時間"),
("die","Krankmeldung","Krankmeldungen","病假通報","工作"),
("das","Attest","Atteste","診斷證明","工作"),
("die","Praxis","Praxen","診所","工作"),
("der","Zahnarzt","Zahnärzte","牙醫（男）","工作"),
("die","Zahnärztin","Zahnärztinnen","牙醫（女）","工作"),
("der","Patient","Patienten","病人（男）","工作"),
("die","Patientin","Patientinnen","病人（女）","工作"),
("die","Apotheke","Apotheken","藥局","工作"),
("das","Pflaster","Pflaster","OK繃","日常"),
("die","Bandage","Bandagen","繃帶","日常"),
("die","Spritze","Spritzen","注射","日常"),
("die","Diät","Diäten","飲食控制","飲食"),
("das","Gewicht","Gewichte","重量","日常"),
("die","Ernährung",None,"營養","飲食"),
("der","Vitamin","Vitamine","維他命","飲食"),
("der","Sportverein","Sportvereine","運動社團","日常"),
("das","Training","Trainings","訓練","日常"),
("der","Wettkampf","Wettkämpfe","比賽","日常"),
("der","Sieg","Siege","勝利","日常"),
("die","Niederlage","Niederlagen","敗北","日常"),
("der","Spieler","Spieler","球員（男）","日常"),
("die","Spielerin","Spielerinnen","球員（女）","日常"),
("der","Trainer","Trainer","教練（男）","日常"),
("die","Trainerin","Trainerinnen","教練（女）","日常"),
("das","Publikum",None,"觀眾","日常"),
("die","Bühne","Bühnen","舞台","日常"),
("der","Schauspieler","Schauspieler","演員（男）","日常"),
("die","Schauspielerin","Schauspielerinnen","演員（女）","日常"),
("der","Sänger","Sänger","歌手（男）","日常"),
("die","Sängerin","Sängerinnen","歌手（女）","日常"),
("die","Ausstellung","Ausstellungen","展覽","旅行"),
("die","Führung","Führungen","導覽","旅行"),
("der","Eintritt",None,"入場費","旅行"),
("die","Ermäßigung","Ermäßigungen","優待折扣","日常"),
("der","Ausweis","Ausweise","證件","日常"),
("die","Mitgliedschaft","Mitgliedschaften","會員資格","日常"),
("der","Verein","Vereine","協會／社團","日常"),
("die","Organisation","Organisationen","組織","工作"),
("das","Projekt","Projekte","專案","工作"),
("die","Veranstaltung","Veranstaltungen","活動","日常"),
("die","Anmeldung","Anmeldungen","報名","工作"),
("die","Teilnahme","Teilnahmen","參加","工作"),
("der","Teilnehmer","Teilnehmer","參加者（男）","工作"),
("die","Teilnehmerin","Teilnehmerinnen","參加者（女）","工作"),
("die","Information","Informationen","資訊","日常"),
("die","Werbung","Werbungen","廣告","日常"),
("die","Anzeige","Anzeigen","啟事／廣告","日常"),
("der","Artikel","Artikel","文章／商品","日常"),
("die","Überschrift","Überschriften","標題","日常"),
("der","Bericht","Berichte","報導","日常"),
("das","Interview","Interviews","訪談","日常"),
("die","Sendung","Sendungen","節目","日常"),
("der","Kanal","Kanäle","頻道","日常"),
("das","Programm","Programme","節目表／程式","日常"),
("die","Nachrichten",None,"新聞","日常"),
("das","Wetter",None,"天氣","自然"),
("die","Prognose","Prognosen","預報","自然"),
("das","Handy","Handys","手機","日常"),
("die","Nummer","Nummern","號碼","日常"),
("die","Vorwahl","Vorwahlen","區碼","日常"),
("das","Gespräch","Gespräche","談話","日常"),
("die","Verbindung","Verbindungen","連線／班次","日常"),
("das","Signal","Signale","訊號","日常"),
("die","Batterie","Batterien","電池","日常"),
("das","Ladegerät","Ladegeräte","充電器","日常"),
("der","Akku","Akkus","充電電池","日常"),
("der","Bildschirm","Bildschirme","螢幕","日常"),
("die","Tastatur","Tastaturen","鍵盤","日常"),
("die","Maus","Mäuse","滑鼠","日常"),
("der","Lautsprecher","Lautsprecher","喇叭","日常"),
("der","Kopfhörer","Kopfhörer","耳機","日常"),
("die","Kamera","Kameras","相機","日常"),
("das","Video","Videos","影片","日常"),
("die","Aufnahme","Aufnahmen","錄音／錄影","日常"),
]:
    w(*row, "A2")

A2_VERBS = [
("erklären","解釋"),("erzählen","講述"),("beschreiben","描述"),
("vergessen","忘記"),("erinnern","記得"),("entscheiden","決定"),
("versuchen","嘗試"),("schaffen","做到"),("erreichen","達成／到達"),
("bekommen","得到"),("erhalten","收到"),("verlieren","失去"),
("gewinnen","贏得"),("verändern","改變"),("verbessern","改善"),
("entwickeln","發展"),("entdecken","發現"),("erleben","經歷"),
("genießen","享受"),("einladen","邀請"),("besuchen","參觀／拜訪"),
("einziehen","搬入"),("ausziehen","搬出"),("umziehen","搬家"),
("bestellen","訂購"),("liefern","送貨"),("umtauschen","退換"),
("reclamieren","申訴"),("reparieren","修理"),("reinigen","清掃"),
("buchen","預訂"),("stornieren","取消預訂"),("parken","停車"),
("überholen","超車"),("abbiegen","轉彎"),("überqueren","穿越"),
("folgen","跟隨"),("zeigen","指出"),("empfehlen","推薦"),
("vorschlagen","提議"),("zustimmen","同意"),("ablehnen","拒絕"),
("versprechen","答應"),("entschuldigen","道歉"),("gratulieren","祝賀"),
("wünschen","祝願"),("hoffen","希望"),("erwarten","期待"),
("planen","計畫"),("vorbereiten","準備"),("wiederholen","複習"),
("üben","練習"),("merken","記住"),("notieren","記下"),
("drucken","列印"),("speichern","儲存"),("herunterladen","下載"),
("hochladen","上傳"),("löschen","刪除"),("funktionieren","運作"),
("klappen","順利"),("passen","適合"),("gefallen","喜歡"),
("schmecken","嚐起來"),("riechen","聞起來"),("klingen","聽起來"),
("wirken","起作用"),("steigen","上升"),("sinken","下降"),
("wachsen","成長"),("sterben","死亡"),("heiraten","結婚"),
("unterstützen","支援"),("teilen","分享"),("sparen","存錢"),
("leihen","出借"),("schulden","欠"),("verdienen","賺得"),
("ausgeben","花費"),("vergleichen","比較"),("wählen","選擇"),
("prüfen","檢查"),("kontrollieren","控管"),("organisieren","組織"),
("feiern","慶祝"),("reisen","旅行"),("wandern","健行"),
("trainieren","訓練"),("sich_ausruhen","休息"),("sich_entspannen","放鬆"),
("sich_beschäftigen","忙於"),("sich_bewerben","求職申請"),
("sich_anmelden","報名／登記"),("sich_abmelden","注销"),
("sich_unterhalten","交談"),("sich_streiten","爭吵"),
("sich_treffen","碰面"),("sich_verabschieden","告別"),
("sich_beeilen","趕緊"),("sich_versäten","遲到"),
("sich_erkälten","感冒"),("sich_fühlen","感覺"),
("sich_ängstigen","害怕"),("sich_sorgen","擔心"),
("sich_freuen","開心"),("sich_ärgern","生氣"),
("sich_interessieren","感興趣"),("sich_vorstellen","自我介紹"),
("sich_erinnern","回想起"),("sich_entscheiden","做決定"),
("sich_bewegen","活動身體"),("sich_waschen","清洗自己"),
("mitbringen","帶來"),("mitnehmen","帶走"),("zurückgeben","歸還"),
("zurückkommen","回來"),("weitergehen","繼續走"),("weiterfahren","繼續行駛"),
("aufpassen","注意"),("aufgeben","放棄"),("anfangen","開始"),
("aufhören","停止"),("einpacken","打包"),("auspacken","拆包"),
("anziehen","穿上"),("ausziehen_kleidung","脫衣服"),
("umziehen_kleidung","換衣服"),("waschen","洗"),("bügeln","熨燙"),
("nähen","縫"),("schneiden","切"),("braten","煎"),("backen","烤"),
("kochen","煮"),("würzen","調味"),("probieren","試吃"),
("servieren","上菜"),("rechnen","計算"),("zählen","數"),
("wiegen","秤"),("messen","量"),("bauen","建造"),("malen","畫"),
("zeichnen","素描"),("basteln","手工"),("sammeln","收集"),
("tauschen","交換"),("schenken","贈送"),("leihen_aus","借出"),
("mieten","租"),("vermieten","出租"),("kündigen","解約"),
("unterschreiben","簽名"),("ausfüllen","填寫"),("abschicken","寄出"),
("ankündigen","宣布"),("berichten","報告"),("informieren","告知"),
("warnen","警告"),("verbieten","禁止"),("erlauben","允許"),
("fordern","要求"),("bitten","請求"),("anbieten","提供"),
("liefern_a2","運送"),("abholen","去取"),("bringen","帶來"),
("schicken","寄送"),("empfangen","接收"),("öffnen","打開"),
("schließen","關閉"),("einschalten","打開開關"),("ausschalten","關上開關"),
("laden","充電／載入"),("starten","啟動"),("beenden","結束"),
("drucken_a2","列印"),("kopieren","影印"),("scannen","掃描"),
("übersetzen","翻譯"),("buchstabieren","拼字母"),("aussprechen","發音"),
("bedeuten","意味著"),("heißen","名叫／意為"),("nennen","稱呼"),
("rufen","呼叫"),("schreien","大叫"),("flüstern","耳語"),
("lächeln","微笑"),("lachen","笑"),("weinen","哭"),("schreien_a2","喊叫"),
("atmen","呼吸"),("husten","咳嗽"),("niesen","打噴嚏"),
("schlucken","吞嚥"),("beißen","咬"),("kauen","咀嚼"),
("riechen_a2","聞"),("schmecken_a2","嚐"),("fühlen","感覺"),
("spüren","感受到"),("bemerken","注意到"),("beobachten","觀察"),
("untersuchen","檢查"),("heilen","治癒"),("impfen","接種"),
("operieren","開刀"),("sterben_a2","死亡"),("leben_a2","生活"),
("geboren werden","出生"),
]
for word, zh in A2_VERBS:
    base = word.replace("_a2","").replace("_kleidung","").replace("_aus","")
    if base.startswith("sich_"):
        base = "sich " + base[5:]
    if base == "ausziehen":
        zh = "搬出／脫下"
    w(None, base, None, zh, "動詞", "A2")

A2_ADJ = [
("nötig","必要的"),("praktisch","實用的"),("unpraktisch","不實用的"),
("bequem","舒服的"),("unbequem","不舒服的"),("gemütlich","愜意的"),
("spannend","精彩的"),("entspannend","放鬆的"),("aufregend","刺激的"),
("nervös","緊張的"),("ruhig","安靜的"),("laut","大聲的"),("leise","小聲的"),
("hell","明亮的"),("dunkel","黑暗的"),("frisch","新鮮的"),("lecker","好吃的"),
("übel","不舒服的"),("scharf","辣的／鋒利的"),("süß","甜的"),
("sauer","酸的"),("salzig","鹹的"),("bitter","苦的"),
("zufrieden","滿意的"),("enttäuscht","失望的"),("überrascht","驚訝的"),
("stolz","驕傲的"),("peinlich","尷尬的"),("höflich","有禮貌的"),
("unhöflich","沒禮貌的"),("geduldig","有耐心的"),("ungeduldig","沒耐心的"),
("ehrlich","誠實的"),("gefährlich","危險的"),("sicher","安全的"),
("unsicher","不確定的"),("ähnlich","相似的"),("besonders","特別的"),
("gewöhnlich","平常的"),("außergewöhnlich","非凡的"),
("einfach","簡單的"),("kompliziert","複雜的"),("modern","現代的"),
("traditionell","傳統的"),("international","國際的"),
("öffentlich","公共的"),("privat","私人的"),("beruflich","職業上的"),
("persönlich","個人的"),("täglich","每天的"),("wöchentlich","每週的"),
("monatlich","每月的"),("jährlich","每年的"),
("sofort","立刻的"),("plötzlich","突然的"),("endlich","終於"),
("ziemlich","相當"),("etwas","有點"),("besonders_adv","特別"),
("überhaupt","根本"),("mindestens","至少"),("höchstens","最多"),
("ungefähr","大約"),("genau","正好"),("fast","幾乎"),
("kaum","幾乎不"),("sogar","甚至"),("nur","只有"),
("auch","也"),("noch","還"),("schon","已經"),
("wieder","再"),("weiter","繼續"),("zurück","回去"),
("vorbei","過去了"),("fertig","完成"),("bereit","準備好"),
("verfügbar","可取得的"),("ausverkauft","售完的"),("beliebt","受歡迎的"),
("bekannt","知名的"),("unbekannt","不知名的"),("erfolgreich","成功的"),
("erfahren","有經驗的"),("geeignet","適合的"),("geeignet_nicht","不合適的"),
("passend","合適的"),("unpassend","不合適的"),("nützlich","有用的"),
("nutzlos","無用的"),("sinnvoll","有意義的"),("sinnlos","無意義的"),
("möglich","可能的"),("unmöglich","不可能的"),("wahrscheinlich","可能的"),
("unwahrscheinlich","不太可能的"),("notwendig","必要的"),
("überflüssig","多餘的"),("dringend","緊急的"),("wichtig","重要的"),
("unwichtig","不重要的"),("ernst","嚴重的"),("locker","輕鬆的"),
("streng","嚴格的"),("tolerant","寬容的"),("offen","開放的"),
("geschlossen","關閉的"),("besetzt","佔用的"),("frei","空的"),
("voll","滿的"),("leer","空的"),("sauber","乾淨的"),("dreckig","髒的"),
("ordentlich","整齊的"),("unordentlich","凌亂的"),
("pünktlich","準時的"),("verspätet","遲到的"),
("freundlich","友善的"),("unfreundlich","不友善的"),
("hilfsbereit","樂於助人的"),("egoistisch","自私的"),
("großzügig","慷慨的"),("sparsam","節儉的"),
("reich","富有的"),("arm","貧窮的"),("teuer","貴的"),("günstig","划算的"),
("wertvoll","珍貴的"),("wertlos","沒價值的"),
("gesund","健康的"),("ungesund","不健康的"),("fit","健康有活力"),
("krank","生病的"),("verletzt","受傷的"),("müde","疲倦的"),
("ausgeschlafen","睡飽的"),("wach","清醒的"),
("hungrig","餓的"),("satt","飽的"),("durstig","渴的"),
("glücklich","幸福的"),("unglücklich","不幸的"),("traurig","悲傷的"),
("fröhlich","愉快的"),("wütend","憤怒的"),("ängstlich","害怕的"),
("mutig","勇敢的"),("schrecklich","可怕的"),("wunderbar","美妙的"),
("fantastisch","極棒的"),("schrecklich_neg","糟的"),("schrecklich2","糟糕的"),
]
for word, zh in A2_ADJ:
    base = word.replace("_adv","").replace("_nicht","").replace("_neg","").replace("2","")
    if base == "geeignet" and "nicht" in word:
        continue
    w(None, base, None, zh, "形容詞", "A2")

# Extra A2 connector / particles as entries
for word, zh in [
("deshalb","因此"),("darum","所以"),("deswegen","因此"),
("trotzdem","儘管如此"),("dennoch","然而"),("außerdem","此外"),
("zudem","再者"),("nämlich","也就是說"),("allerdings","不過"),
("jedoch","然而"),("obwohl","雖然"),("weil","因為"),
("denn","因為（並列）"),("wenn","如果／當"),("als","當（過去）"),
("während","在…期間"),("bevor","在…之前"),("nachdem","在…之後"),
("bis","直到"),("seit","自從"),("damit","以便"),
("sodass","以至於"),("falls","萬一"),("ob","是否"),
("entweder","要麼"),("oder","或者"),("weder","既不"),
("noch_weder","也不"),("sowohl","不但"),("als_auch","而且"),
("je","越…"),("desto","就越…"),
]:
    cat = "日常"
    w(None, word.replace("_weder","").replace("_auch",""), None, zh, cat, "A2")

# More A1/A2 nouns to push completeness - countries, languages, school subjects, etc.
for word, zh, level in [
("Deutschland","德國","A1"),("Österreich","奧地利","A1"),("die Schweiz","瑞士","A1"),
("Frankreich","法國","A1"),("Italien","義大利","A1"),("Spanien","西班牙","A1"),
("England","英國","A1"),("Amerika","美國","A1"),("China","中國","A1"),
("Japan","日本","A1"),("Taiwan","台灣","A1"),("Europa","歐洲","A1"),
("Asien","亞洲","A1"),("Afrika","非洲","A2"),("Australien","澳洲","A2"),
("Berlin","柏林","A1"),("München","慕尼黑","A1"),("Hamburg","漢堡","A1"),
("Köln","科隆","A1"),("Frankfurt","法蘭克福","A1"),("Wien","維也納","A1"),
("Zürich","蘇黎世","A2"),("Deutsch","德文","A1"),("Englisch","英文","A1"),
("Französisch","法文","A1"),("Spanisch","西班牙文","A1"),("Chinesisch","中文","A1"),
("Mathematik","數學","A1"),("Biologie","生物","A2"),("Chemie","化學","A2"),
("Physik","物理","A2"),("Geschichte","歷史","A2"),("Geografie","地理","A2"),
("Kunst","藝術","A1"),("Sport","體育","A1"),("Religion","宗教","A2"),
("Informatik","資訊","A2"),("Wirtschaft","經濟","A2"),("Politik","政治","A2"),
]:
    article = None
    real = word
    if word.startswith("die "):
        article, real = "die", word[4:]
    w(article, real, None, zh, "日常", level)

# School / office supplies more
for row, level in [
(( "der","Ordner","Ordner","資料夾","工作"), "A2"),
(( "die","Mappe","Mappen","文件夾","工作"), "A2"),
(( "der","Ordner","Ordner","活頁夾","工作"), "A2"),
(( "die","Klammer","Klammern","迴紋針","工作"), "A2"),
(( "der","Locher","Locher","打孔機","工作"), "A2"),
(( "der","Tacker","Tacker","釘書機","工作"), "A2"),
(( "die","Schere","Scheren","剪刀","日常"), "A1"),
(( "der","Klebstoff","Klebstoffe","膠水","日常"), "A2"),
(( "das","Lineal","Lineale","尺","日常"), "A1"),
(( "der","Spitzer","Spitzer","削鉛筆機","日常"), "A1"),
(( "die","Tafel","Tafeln","黑板","工作"), "A1"),
(( "der","Kreide","-", "粉筆","工作"), "A1"),
(( "der","Beamer","Beamer","投影機","工作"), "A2"),
(( "die","Folie","Folien","投影片","工作"), "A2"),
]:
    article, word, plural, zh, cat = row
    if plural == "-":
        plural = None
    w(article, word, plural, zh, cat, level)

# Emotions / abstract A2
for row in [
("die","Freude","Freuden","喜悅","日常"),
("die","Trauer",None,"悲傷","日常"),
("die","Angst","Ängste","恐懼","日常"),
("der","Ärger",None,"惱怒","日常"),
("die","Liebe",None,"愛","日常"),
("der","Hass",None,"恨","日常"),
("die","Hoffnung","Hoffnungen","希望","日常"),
("die","Sorge","Sorgen","擔心","日常"),
("der","Stress",None,"壓力","日常"),
("die","Ruhe",None,"安靜／休息","日常"),
("die","Kraft","Kräfte","力量","日常"),
("die","Schwäche","Schwächen","弱點","日常"),
("die","Chance","Chancen","機會","日常"),
("das","Risiko","Risiken","風險","日常"),
("der","Vorteil","Vorteile","優點","日常"),
("der","Nachteil","Nachteile","缺點","日常"),
("der","Zweck","Zwecke","目的","日常"),
("der","Sinn",None,"意義","日常"),
("der","Wert","Werte","價值","日常"),
("die","Qualität","Qualitäten","品質","日常"),
("die","Menge","Mengen","數量","日常"),
("die","Zahl","Zahlen","數字","數字"),
("die","Summe","Summen","總和","數字"),
("der","Durchschnitt","Durchschnitte","平均","數字"),
("das","Prozent","Prozent","百分之","數字"),
("die","Hälfte","Hälften","一半","數字"),
("das","Viertel","Viertel","四分之一","數字"),
("die","Mehrheit","Mehrheiten","多數","日常"),
("die","Minderheit","Minderheiten","少數","日常"),
]:
    w(*row, "A2")


# ===================== EXTRA BATCH for completeness =====================
# Household verbs/nouns, city, feelings, grammar words, more A1 nouns
EXTRA_A1 = [
("das","Regal","Regale","書架","日常"),
("die","Kommode","Kommoden","斗櫃","日常"),
("der","Nachttisch","Nachttische","床頭櫃","日常"),
("die","Schublade","Schubladen","抽屜","日常"),
("der","Haken","Haken","掛鉤","日常"),
("die","Steckdose","Steckdosen","插座","日常"),
("der","Schalter","Schalter","開關","日常"),
("die","Birne","Birnen","燈泡／梨","日常"),
("das","Kabel","Kabel","電線","日常"),
("der","Stecker","Stecker","插頭","日常"),
("die","Kerze","Kerzen","蠟燭","日常"),
("das","Streichholz","Streichhölzer","火柴","日常"),
("das","Feuerzeug","Feuerzeuge","打火機","日常"),
("der","Eimer","Eimer","水桶","日常"),
("der","Besen","Besen","掃帚","日常"),
("das","Putztuch","Putztücher","抹布","日常"),
("das","Waschmittel",None,"洗衣精","日常"),
("die","Spülung","Spülungen","柔軟精／沖洗","日常"),
("der","Müllbeutel","Müllbeutel","垃圾袋","日常"),
("die","Zeitung","Zeitungen","報紙","日常"),
("die","Zeitschrift","Zeitschriften","雜誌","日常"),
("der","Roman","Romane","小說","日常"),
("das","Märchen","Märchen","童話","日常"),
("das","Gedicht","Gedichte","詩","日常"),
("die","Geschichte","Geschichten","故事／歷史","日常"),
("die","Nachricht","Nachrichten","消息","日常"),
("der","Brief","Briefe","信","日常"),
("die","Karte","Karten","卡片／地圖","日常"),
("die","Postkarte","Postkarten","明信片","日常"),
("das","Paket","Pakete","包裹","日常"),
("die","Marke","Marken","郵票／品牌","日常"),
("der","Absender","Absender","寄件人","日常"),
("der","Empfänger","Empfänger","收件人","日常"),
("die","Liebe","-", "愛","日常"),
("der","Hass","-", "恨","日常"),
("die","Angst","Ängste","害怕","日常"),
("die","Freude","Freuden","快樂","日常"),
("der","Spaß","-", "樂趣","日常"),
("die","Langeweile","-", "無聊","日常"),
("der","Witz","Witze","笑話","日常"),
("das","Glück","-", "幸運／幸福","日常"),
("das","Pech","-", "倒霉","日常"),
("der","Erfolg","Erfolge","成功","日常"),
("der","Fehler","Fehler","錯誤","日常"),
("die","Chance","Chancen","機會","日常"),
("das","Problem","Probleme","問題","日常"),
("die","Sache","Sachen","事情／東西","日常"),
("das","Ding","Dinge","東西","日常"),
("der","Teil","Teile","部分","日常"),
("das","Stück","Stücke","塊／件","日常"),
("die","Art","Arten","種類","日常"),
("die","Form","Formen","形狀","日常"),
("die","Gruppe","Gruppen","團體","日常"),
("das","Paar","Paare","一對","日常"),
("die","Menge","Mengen","許多／量","日常"),
("die","Liste","Listen","清單","日常"),
("der","Plan","Pläne","計畫","日常"),
("die","Idee","Ideen","想法","日常"),
("der","Traum","Träume","夢","日常"),
("das","Ziel","Ziele","目標","日常"),
("der","Weg","Wege","路／方法","日常"),
("der","Grund","Gründe","理由","日常"),
("das","Beispiel","Beispiele","例子","日常"),
("die","Frage","Fragen","問題","日常"),
("die","Antwort","Antworten","答案","日常"),
("das","Gespräch","Gespräche","談話","日常"),
("das","Thema","Themen","主題","日常"),
("die","Meinung","Meinungen","意見","日常"),
("der","Vorschlag","Vorschläge","建議","日常"),
("die","Bitte","Bitten","請求","日常"),
("der","Dank","-", "感謝","日常"),
("die","Entschuldigung","Entschuldigungen","道歉","日常"),
("der","Glückwunsch","Glückwünsche","祝賀","日常"),
("die","Hilfe","Hilfen","幫助","日常"),
("die","Information","Informationen","資訊","日常"),
("die","Erklärung","Erklärungen","說明","日常"),
("die","Übersetzung","Übersetzungen","翻譯","日常"),
("die","Bedeutung","Bedeutungen","意思","日常"),
("das","Zeichen","Zeichen","記號","日常"),
("der","Punkt","Punkte","點","日常"),
("die","Linie","Linien","線","日常"),
("der","Kreis","Kreise","圓","日常"),
("das","Quadrat","Quadrate","正方形","日常"),
("das","Dreieck","Dreiecke","三角形","日常"),
("die","Seite","Seiten","邊／頁","日常"),
("die","Mitte","-", "中間","日常"),
("der","Anfang","Anfänge","開始","日常"),
("das","Ende","Enden","結束","日常"),
("die","Pause","Pausen","休息","日常"),
("die","Zeit","Zeiten","時間","時間"),
("der","Moment","Momente","片刻","時間"),
("die","Zukunft","-", "未來","時間"),
("die","Vergangenheit","-", "過去","時間"),
("die","Gegenwart","-", "現在","時間"),
("die","Uhrzeit","Uhrzeiten","時刻","時間"),
("das","Datum","Daten","日期","時間"),
("der","Kalender","Kalender","日曆","時間"),
("der","Termin","Termine","約定","時間"),
("die","Verabredung","Verabredungen","約會","時間"),
("die","Einladung","Einladungen","邀請","家庭"),
("das","Geschenk","Geschenke","禮物","家庭"),
("die","Überraschung","Überraschungen","驚喜","家庭"),
("die","Feier","Feiern","慶祝","家庭"),
("die","Party","Partys","派對","家庭"),
("das","Fest","Feste","節日","家庭"),
("Weihnachten","-","聖誕節","時間"),
("Ostern","-","復活節","時間"),
("Silvester","-","跨年","時間"),
("der","Geburtstag","Geburtstage","生日","家庭"),
("der","Urlaub","Urlaube","假期","旅行"),
("die","Reise","Reisen","旅行","旅行"),
("der","Ausflug","Ausflüge","郊遊","旅行"),
("das","Abenteuer","Abenteuer","冒險","旅行"),
("die","Erfahrung","Erfahrungen","經驗","日常"),
("die","Erinnerung","Erinnerungen","回憶","日常"),
("das","Erlebnis","Erlebnisse","經歷","日常"),
("die","Fantasie","Fantasien","想像","日常"),
("die","Realität","Realitäten","現實","日常"),
("die","Wahrheit","Wahrheiten","真相","日常"),
("die","Lüge","Lügen","謊言","日常"),
("das","Geheimnis","Geheimnisse","秘密","日常"),
("der","Witz","Witze","玩笑","日常"),
("der","Ernst","-", "認真","日常"),
]

for item in EXTRA_A1:
    if len(item)==5:
        article, word, plural, zh, cat = item
        if plural == "-": plural = None
        w(article if article not in (None,"-") else None, word, plural, zh, cat, "A1")
    elif len(item)==4:
        word, plural, zh, cat = item
        w(None, word, None if plural=="-" else plural, zh, cat, "A1")

EXTRA_A1_VERBS = [
("abschließen","完成／鎖上"),("anfangen","開始"),("ankommen","到達"),
("anrufen","打電話給"),("ansehen","觀看"),("antworten","回答"),
("arbeiten","工作"),("aufhören","停止"),("aufräumen","整理"),
("aufstehen","起床"),("ausgeben","花費"),("aussehen","看起來"),
("aussteigen","下車"),("baden","泡澡"),("bauen","建造"),
("bedeuten","意味著"),("beginnen","開始"),("bekommen","得到"),
("bestellen","訂"),("besuchen","拜訪"),("bezahlen","付"),
("bieten","提供"),("bilden","形成"),("bleiben","留下"),
("blicken","望"),("brauchen","需要"),("bringen","帶來"),
("dauern","持續"),("decken","鋪／遮"),("denken","想"),
("duschen","沖澡"),("einkaufen","購物"),("einladen","邀請"),
("einsteigen","上車"),("empfangen","接收"),("empfinden","感受"),
("enden","結束"),("enthalten","含有"),("entschuldigen","道歉"),
("erinnern","提醒"),("erklären","解釋"),("erlauben","允許"),
("erzählen","講述"),("essen","吃"),("fahren","行駛"),
("fallen","落下"),("finden","找到"),("fliegen","飛"),
("folgen","跟隨"),("fragen","問"),("freuen","使高興"),
("fühlen","感覺"),("führen","帶領"),("füllen","裝滿"),
("geben","給"),("gefallen","喜歡"),("gehen","去"),
("gehören","屬於"),("gewinnen","贏得"),("glauben","相信"),
("gratulieren","祝賀"),("grüßen","打招呼"),("haben","有"),
("halten","握住／停"),("handeln","行動／交易"),("hängen","掛"),
("hassen","恨"),("heben","舉起"),("heiraten","結婚"),
("heißen","名叫"),("helfen","幫助"),("herstellen","製造"),
("hoffen","希望"),("holen","去拿"),("hören","聽"),
("interessieren","感興趣"),("kaufen","買"),("kennen","認識"),
("klären","澄清"),("klingen","聽起來"),("kochen","煮"),
("kommen","來"),("können","能"),("kosten","花費"),
("kriegen","得到（口語）"),("kümmern","照顧"),("lachen","笑"),
("lassen","讓／留下"),("laufen","跑"),("leben","生活"),
("legen","放置"),("leihen","借"),("lernen","學"),
("lesen","讀"),("lieben","愛"),("liefern","送貨"),
("liegen","躺"),("loben","稱讚"),("löschen","刪除／滅火"),
("machen","做"),("malen","畫"),("meinen","認為"),
("merken","注意／記住"),("mieten","租"),("mögen","喜歡"),
("müssen","必須"),("nehmen","拿"),("nennen","稱呼"),
("öffnen","打開"),("ordnen","整理"),("packen","打包"),
("passen","適合"),("passieren","發生"),("planen","計畫"),
("probieren","試"),("prüfen","檢查"),("putzen","擦洗"),
("raten","猜測／建議"),("rauchen","抽菸"),("räumen","清理"),
("rechnen","計算"),("reden","說話"),("reisen","旅行"),
("rennen","奔跑"),("reparieren","修理"),("retten","拯救"),
("riechen","聞"),("rufen","叫"),("sagen","說"),
("sammeln","收集"),("schaffen","做到"),("schauen","看"),
("scheinen","似乎／照耀"),("schenken","贈送"),("schicken","寄"),
("schieben","推"),("schießen","射"),("schlafen","睡"),
("schlagen","打"),("schließen","關"),("schmecken","嚐"),
("schneiden","切"),("schreiben","寫"),("schreien","喊"),
("schweigen","沉默"),("schwimmen","游"),("sehen","看"),
("sein","是"),("senden","發送"),("setzen","放置"),
("singen","唱"),("sinken","下沉"),("sitzen","坐"),
("sollen","應該"),("sparen","存"),("spielen","玩"),
("sprechen","說"),("springen","跳"),("stehen","站"),
("steigen","登"),("stellen","放"),("sterben","死"),
("stimmen","正確／投票"),("stoppen","停止"),("stoßen","撞"),
("streichen","塗／刪"),("streiten","爭吵"),("studieren","讀大學"),
("suchen","找"),("tanzen","跳舞"),("teilen","分享"),
("telefonieren","打電話"),("tragen","穿／提"),("träumen","做夢"),
("treffen","遇見"),("trinken","喝"),("tun","做"),
("üben","練習"),("überlegen","考慮"),("überraschen","驚喜"),
("überweisen","匯款"),("umarmen","擁抱"),("umsehen","環顧"),
("unterschreiben","簽名"),("unterstützen","支持"),("untersuchen","檢查"),
("verdienen","賺"),("vereinbaren","約定"),("vergessen","忘"),
("vergleichen","比較"),("verkaufen","賣"),("verlassen","離開"),
("verlieren","失去"),("vermeiden","避免"),("vermissen","想念"),
("versprechen","答應"),("verstehen","懂"),("versuchen","嘗試"),
("verwenden","使用"),("verzeihen","原諒"),("vorbereiten","準備"),
("vorschlagen","提議"),("vorstellen","介紹"),("wählen","選擇"),
("wachen","醒著"),("wachsen","成長"),("wagen","敢"),
("warten","等"),("waschen","洗"),("wecken","叫醒"),
("wechseln","更換"),("wecken","叫醒"),("weinen","哭"),
("wenden","轉向"),("werden","變成"),("werfen","扔"),
("wissen","知道"),("wohnen","住"),("wünschen","希望"),
("zahlen","付錢"),("zählen","數"),("zeichnen","畫"),
("zeigen","展示"),("zerstören","破壞"),("ziehen","拉"),
("zuhören","聆聽"),("zustimmen","同意"),("zurückkommen","回來"),
("zusagen","答應"),("zusammenarbeiten","合作"),("zwingen","強迫"),
]
for word, zh in EXTRA_A1_VERBS:
    w(None, word, None, zh, "動詞", "A1")

EXTRA_A2_NOUNS = [
("die","Abwesenheit","Abwesenheiten","缺席","工作"),
("die","Anwesenheit","Anwesenheiten","出席","工作"),
("die","Aufmerksamkeit","Aufmerksamkeiten","注意力","日常"),
("die","Bedingung","Bedingungen","條件","工作"),
("die","Begeisterung","Begeisterungen","熱情","日常"),
("die","Behandlung","Behandlungen","治療／對待","日常"),
("die","Beobachtung","Beobachtungen","觀察","日常"),
("die","Beratung","Beratungen","諮詢","工作"),
("die","Beschreibung","Beschreibungen","描述","日常"),
("die","Besprechung","Besprechungen","會議","工作"),
("die","Bestätigung","Bestätigungen","確認","工作"),
("die","Beziehung","Beziehungen","關係","家庭"),
("die","Bildung","-", "教育","工作"),
("die","Darstellung","Darstellungen","呈現","工作"),
("die","Diskussion","Diskussionen","討論","工作"),
("die","Eigenschaft","Eigenschaften","特性","日常"),
("die","Einrichtung","Einrichtungen","設施","日常"),
("die","Einstellung","Einstellungen","態度／設定","工作"),
("die","Entscheidung","Entscheidungen","決定","日常"),
("die","Entwicklung","Entwicklungen","發展","工作"),
("die","Erde","-", "地球／泥土","自然"),
("die","Erfindung","Erfindungen","發明","工作"),
("die","Erlaubnis","Erlaubnisse","許可","工作"),
("die","Ermäßigung","Ermäßigungen","減免","日常"),
("die","Erscheinung","Erscheinungen","現象","日常"),
("die","Erwartung","Erwartungen","期待","日常"),
("die","Erweiterung","Erweiterungen","擴充","工作"),
("die","Fähigkeit","Fähigkeiten","能力","工作"),
("die","Feststellung","Feststellungen","判定","工作"),
("die","Flüssigkeit","Flüssigkeiten","液體","飲食"),
("die","Forschung","Forschungen","研究","工作"),
("die","Forderung","Forderungen","要求","工作"),
("die","Führung","Führungen","領導／導覽","工作"),
("die","Funktion","Funktionen","功能","日常"),
("die","Geduld","-", "耐心","日常"),
("die","Gefahr","Gefahren","危險","日常"),
("die","Gelegenheit","Gelegenheiten","機會","日常"),
("die","Gemeinde","Gemeinden","社區／市鎮","日常"),
("die","Genehmigung","Genehmigungen","核准","工作"),
("die","Gerechtigkeit","-", "正義","日常"),
("die","Gesellschaft","Gesellschaften","社會","日常"),
("die","Gestaltung","Gestaltungen","設計","工作"),
("die","Gewohnheit","Gewohnheiten","習慣","日常"),
("die","Grundlage","Grundlagen","基礎","工作"),
("die","Handlung","Handlungen","行為","日常"),
("die","Herstellung","Herstellungen","製造","工作"),
("die","Hilfeleistung","Hilfeleistungen","協助","日常"),
("die","Hoffnung","Hoffnungen","希望","日常"),
("die","Identität","Identitäten","身分","日常"),
("die","Industrie","Industrien","工業","工作"),
("die","Innovation","Innovationen","創新","工作"),
("die","Investition","Investitionen","投資","工作"),
("die","Kennzeichnung","Kennzeichnungen","標示","日常"),
("die","Klage","Klagen","申訴／抱怨","日常"),
("die","Kooperation","Kooperationen","合作","工作"),
("die","Kraft","Kräfte","力量","日常"),
("die","Krise","Krisen","危機","日常"),
("die","Kritik","Kritiken","批評","日常"),
("die","Kultur","Kulturen","文化","日常"),
("die","Leistung","Leistungen","表現／成績","工作"),
("die","Lösung","Lösungen","解決方案","日常"),
("die","Maßnahme","Maßnahmen","措施","工作"),
("die","Möglichkeit","Möglichkeiten","可能性","日常"),
("die","Nachhaltigkeit","-", "永續","自然"),
("die","Nachricht","Nachrichten","消息","日常"),
("die","Öffentlichkeit","-", "公眾","日常"),
("die","Ordnung","Ordnungen","秩序","日常"),
("die","Organisation","Organisationen","組織","工作"),
("die","Persönlichkeit","Persönlichkeiten","性格／名人","日常"),
("die","Pflege","-", "照護","日常"),
("die","Planung","Planungen","規劃","工作"),
("die","Position","Positionen","位置／職位","工作"),
("die","Praxis","Praxen","實務／診所","工作"),
("die","Qualität","Qualitäten","品質","日常"),
("die","Reaktion","Reaktionen","反應","日常"),
("die","Rechnung","Rechnungen","帳單","日常"),
("die","Regierung","Regierungen","政府","日常"),
("die","Region","Regionen","區域","旅行"),
("die","Religion","Religionen","宗教","日常"),
("die","Situation","Situationen","情況","日常"),
("die","Sorgfalt","-", "謹慎","日常"),
("die","Spannung","Spannungen","張力／緊張","日常"),
("die","Spezialität","Spezialitäten","特色","飲食"),
("die","Stelle","Stellen","位置／職缺","工作"),
("die","Steuerung","Steuerungen","控制","工作"),
("die","Stimme","Stimmen","聲音／選票","日常"),
("die","Stimmung","Stimmungen","氣氛","日常"),
("die","Störung","Störungen","干擾／故障","日常"),
("die","Strategie","Strategien","策略","工作"),
("die","Struktur","Strukturen","結構","工作"),
("die","Unterstützung","Unterstützungen","支援","日常"),
("die","Veränderung","Veränderungen","改變","日常"),
("die","Verbindung","Verbindungen","連結","日常"),
("die","Vereinbarung","Vereinbarungen","協議","工作"),
("die","Vergangenheit","-", "過去","時間"),
("die","Verhandlung","Verhandlungen","談判","工作"),
("die","Verhinderung","Verhinderungen","阻礙","日常"),
("die","Verletzung","Verletzungen","傷害","日常"),
("die","Vermittlung","Vermittlungen","仲介","工作"),
("die","Verpflichtung","Verpflichtungen","義務","工作"),
("die","Verschmutzung","Verschmutzungen","污染","自然"),
("die","Versicherung","Versicherungen","保險","日常"),
("die","Verstärkung","Verstärkungen","加強","日常"),
("die","Verteilung","Verteilungen","分配","工作"),
("die","Verwaltung","Verwaltungen","行政","工作"),
("die","Vorbereitung","Vorbereitungen","準備","日常"),
("die","Voraussetzung","Voraussetzungen","前提","工作"),
("die","Vorstellung","Vorstellungen","想像／面試","工作"),
("die","Wachsamkeit","-", "警覺","日常"),
("die","Wahrnehmung","Wahrnehmungen","知覺","日常"),
("die","Warnung","Warnungen","警告","日常"),
("die","Weiterbildung","Weiterbildungen","進修","工作"),
("die","Wirkung","Wirkungen","效果","日常"),
("die","Wirtschaft","-", "經濟","工作"),
("die","Wissenschaft","Wissenschaften","科學","工作"),
("die","Wohnungssuche","-", "找房子","家庭"),
("die","Zusammenarbeit","Zusammenarbeiten","合作","工作"),
("die","Zusammenfassung","Zusammenfassungen","摘要","工作"),
("die","Zustimmung","Zustimmungen","同意","日常"),
("die","Zuverlässigkeit","-", "可靠","日常"),
("der","Abschnitt","Abschnitte","段落／路段","日常"),
("der","Abschluss","Abschlüsse","結束／畢業","工作"),
("der","Absender","Absender","寄件者","日常"),
("der","Abstand","Abstände","距離","日常"),
("der","Abfall","Abfälle","廢棄物","自然"),
("der","Ablauf","Abläufe","流程","工作"),
("der","Abschnitt","Abschnitte","章節","工作"),
("der","Alltag","-", "日常生活","日常"),
("der","Anspruch","Ansprüche","要求／權利","工作"),
("der","Anteil","Anteile","份額","日常"),
("der","Antrag","Anträge","申請書","工作"),
("der","Antrieb","Antriebe","動力","工作"),
("der","Anzug","Anzüge","西裝","日常"),
("der","Aspekt","Aspekte","面向","工作"),
("der","Auftrag","Aufträge","委託","工作"),
("der","Aufwand","-", "花費心力","工作"),
("der","Ausdruck","Ausdrücke","表達","日常"),
("der","Ausflug","Ausflüge","出遊","旅行"),
("der","Ausgleich","Ausgleiche","平衡","日常"),
("der","Ausweis","Ausweise","證件","日常"),
("der","Bau","Bauten","建築","日常"),
("der","Bedarf","-", "需求","日常"),
("der","Begriff","Begriffe","概念","日常"),
("der","Beitrag","Beiträge","貢獻／費用","工作"),
("der","Bereich","Bereiche","領域","工作"),
("der","Beruf","Berufe","職業","工作"),
("der","Bescheid","Bescheide","通知","工作"),
("der","Besitz","-", "所有","日常"),
("der","Betrieb","Betriebe","企業／運轉","工作"),
("der","Beweis","Beweise","證據","日常"),
("der","Bewohner","Bewohner","居民","家庭"),
("der","Blick","Blicke","目光","日常"),
("der","Bürger","Bürger","公民","日常"),
("der","Charakter","Charaktere","性格","日常"),
("der","Datenschutz","-", "個資保護","工作"),
("der","Druck","-", "壓力／印刷","日常"),
("der","Eindruck","Eindrücke","印象","日常"),
("der","Einfluss","Einflüsse","影響","日常"),
("der","Eintritt","Eintritte","入場","旅行"),
("der","Empfang","Empfänge","接待","旅行"),
("der","Ersatz","-", "替代","日常"),
("der","Erwachsene","Erwachsenen","成人","家庭"),
("der","Fachmann","Fachleute","專家","工作"),
("der","Fall","Fälle","情況／案件","日常"),
("der","Fortschritt","Fortschritte","進步","工作"),
("der","Gastgeber","Gastgeber","主人","家庭"),
("der","Gegenstand","Gegenstände","物品","日常"),
("der","Gegner","Gegner","對手","日常"),
("der","Genuss","Genüsse","享受","飲食"),
("der","Geruch","Gerüche","氣味","日常"),
("der","Geschmack","Geschmäcker","味道／品味","飲食"),
("der","Gewinn","Gewinne","獲利","工作"),
("der","Grad","Grade","程度／度數","日常"),
("der","Grundsatz","Grundsätze","原則","工作"),
("der","Handel","-", "貿易","工作"),
("der","Hintergrund","Hintergründe","背景","日常"),
("der","Inhalt","Inhalte","內容","日常"),
("der","Kampf","Kämpfe","戰鬥","日常"),
("der","Kandidat","Kandidaten","候選人","工作"),
("der","Kauf","Käufe","購買","日常"),
("der","Kompromiss","Kompromisse","妥協","日常"),
("der","Kontakt","Kontakte","聯絡","日常"),
("der","Kreis","Kreise","圈子","日常"),
("der","Kunde","Kunden","客戶","工作"),
("der","Kurs","Kurse","課程／匯率","工作"),
("der","Mangel","Mängel","缺乏","日常"),
("der","Markt","Märkte","市場","日常"),
("der","Mitarbeiter","Mitarbeiter","員工","工作"),
("der","Nachweis","Nachweise","證明","工作"),
("der","Nutzen","-", "益處","日常"),
("der","Partner","Partner","夥伴","家庭"),
("der","Prozess","Prozesse","過程","工作"),
("der","Rahmen","Rahmen","框架","工作"),
("der","Ratschlag","Ratschläge","忠告","日常"),
("der","Raum","Räume","空間","日常"),
("der","Schutz","-", "保護","日常"),
("der","Schwerpunkt","Schwerpunkte","重點","工作"),
("der","Sieg","Siege","勝利","日常"),
("der","Sinn","Sinne","意義／感官","日常"),
("der","Sitz","Sitze","座位／所在地","日常"),
("der","Standard","Standards","標準","工作"),
("der","Standpunkt","Standpunkte","立場","日常"),
("der","Stoff","Stoffe","材料／布料","日常"),
("der","Streit","Streite","爭執","日常"),
("der","Strom","Ströme","電流／潮流","日常"),
("der","Stuhl","Stühle","椅子","日常"),
("der","Sturm","Stürme","暴風雨","自然"),
("der","Teilnehmer","Teilnehmer","參與者","工作"),
("der","Ton","Töne","音調／語氣","日常"),
("der","Umgang","-", "相處／處理","日常"),
("der","Unterricht","-", "教學","工作"),
("der","Unterschied","Unterschiede","差異","日常"),
("der","Ursprung","Ursprünge","起源","日常"),
("der","Verbrauch","-", "消耗","日常"),
("der","Verein","Vereine","社團","日常"),
("der","Verlust","Verluste","損失","日常"),
("der","Versuch","Versuche","嘗試","日常"),
("der","Vertrag","Verträge","契約","工作"),
("der","Vorgang","Vorgänge","過程","工作"),
("der","Vorschlag","Vorschläge","提案","日常"),
("der","Vortrag","Vorträge","演講","工作"),
("der","Vorteil","Vorteile","優點","日常"),
("der","Vorwurf","Vorwürfe","指責","日常"),
("der","Wandel","-", "轉變","日常"),
("der","Wunsch","Wünsche","願望","日常"),
("der","Zustand","Zustände","狀態","日常"),
("der","Zweck","Zwecke","目的","日常"),
("das","Abenteuer","Abenteuer","冒險","旅行"),
("das","Angebot","Angebote","報價／特價","日常"),
("das","Anliegen","Anliegen","訴求","日常"),
("das","Anzeichen","Anzeichen","徵兆","日常"),
("das","Argument","Argumente","論點","日常"),
("das","Bedürfnis","Bedürfnisse","需求","日常"),
("das","Verhalten","-", "行為","日常"),
("das","Verhältnis","Verhältnisse","關係／比例","日常"),
("das","Verfahren","Verfahren","程序","工作"),
("das","Vergnügen","Vergnügen","樂趣","日常"),
("das","Verkehrsmittel","Verkehrsmittel","交通工具","旅行"),
("das","Vermögen","Vermögen","財產","日常"),
("das","Verständnis","-", "理解","日常"),
("das","Vertrauen","-", "信任","日常"),
("das","Volk","Völker","民族","日常"),
("das","Vorhaben","Vorhaben","打算","日常"),
("das","Wachstum","-", "成長","工作"),
("das","Wahrzeichen","Wahrzeichen","地標","旅行"),
("das","Werkzeug","Werkzeuge","工具","工作"),
("das","Wissen","-", "知識","工作"),
("das","Wunder","Wunder","奇蹟","日常"),
("das","Zeichen","Zeichen","符號","日常"),
("das","Zeugnis","Zeugnisse","證明／成績單","工作"),
("das","Ziel","Ziele","目標","日常"),
]
for article, word, plural, zh, cat in EXTRA_A2_NOUNS:
    if plural == "-": plural = None
    w(article, word, plural, zh, cat, "A2")

EXTRA_A2_VERBS = [
("abgeben","交出"),("abhängen","取決於"),("ablehnen","拒絕"),
("abnehmen","減少／減肥"),("abschließen","締結／完成"),("abstellen","關掉／放置"),
("abwarten","等待觀望"),("ändern","改變"),("anerkennen","承認"),
("ankündigen","預告"),("anmelden","登記"),("anpassen","調整"),
("anprobieren","試穿"),("anschauen","觀看"),("anvertrauen","託付"),
("ärgern","惹惱"),("auffallen","引人注意"),("aufgeben","放棄"),
("aufnehmen","錄取／錄製"),("aufpassen","注意"),("ausdrücken","表達"),
("ausfallen","取消／掉髮"),("ausfüllen","填寫"),("ausmachen","約定／關掉"),
("ausreichen","足夠"),("ausschließen","排除"),("aussuchen","挑選"),
("austauschen","交換"),("auswirken","影響"),("beantragen","申請"),
("bearbeiten","處理"),("bedienen","服務／操作"),("beeinflussen","影響"),
("beenden","結束"),("befassen","從事"),("befinden","處於"),
("befürchten","擔心"),("begeistern","使熱衷"),("begleiten","陪伴"),
("behalten","保留"),("behandeln","對待／治療"),("behaupten","聲稱"),
("beherrschen","精通"),("beitragen","貢獻"),("bekanntgeben","公布"),
("beklagen","抱怨"),("bekommen","獲得"),("bemühen","努力"),
("benötigen","需要"),("benutzen","使用"),("beobachten","觀察"),
("beraten","諮詢"),("berichten","報告"),("berücksichtigen","考慮到"),
("beruhigen","安撫"),("beschäftigen","使忙碌"),("beschleunigen","加速"),
("beschränken","限制"),("beschreiben","描述"),("beseitigen","排除"),
("besitzen","擁有"),("bestehen","通過／存在"),("bestätigen","確認"),
("bestimmen","決定"),("beten","祈禱"),("betrachten","觀看"),
("betragen","總計"),("betreffen","涉及"),("betreiben","經營"),
("betreten","進入"),("betrügen","欺騙"),("bewegen","移動"),
("beweisen","證明"),("bewerben","應徵"),("bewundern","欣賞"),
("bezeichnen","稱作"),("beziehen","涉及／訂閱"),("bieten","提供"),
("bilden","構成"),("bitten","請求"),("bleiben","停留"),
("blühen","開花"),("braten","煎烤"),("brauchen","需要"),
("brechen","打破"),("brennen","燃燒"),("bringen","帶來"),
("buchen","預訂"),("dämmen","減緩"),("darstellen","描述／演出"),
("dauern","持續"),("decken","覆蓋"),("definieren","定義"),
("demokratisieren","民主化"),("demonstrieren","示威／示範"),("denken","思考"),
("diskutieren","討論"),("dokumentieren","記錄"),("drücken","按壓"),
("dulden","容忍"),("durchführen","執行"),("durchsetzen","貫徹"),
("einbeziehen","納入"),("einfallen","想起"),("einführen","引進"),
("eingeben","輸入"),("eingehen","進入／答應"),("einhalten","遵守"),
("einigen","達成一致"),("einlassen","讓進"),("einlegen","放入"),
("einnehmen","服用／佔有"),("einrichten","布置"),("einschätzen","評估"),
("einschlafen","入睡"),("einschließen","包含"),("einsetzen","投入"),
("einsteigen","上車／入門"),("eintreten","發生／進入"),("einwandern","移入"),
("einwirken","作用"),("empfangen","接待"),("empfehlen","推薦"),
("empfinden","感覺"),("enden","結束"),("engagieren","投入"),
("entfernen","移除"),("enthalten","包含"),("entkommen","逃脫"),
("entlanggehen","沿著走"),("entlassen","解雇"),("entscheiden","決定"),
("entschließen","下決心"),("entsorgen","丟棄"),("entspannen","放鬆"),
("entsprechen","符合"),("entstehen","產生"),("enttäuschen","使失望"),
("entwickeln","發展"),("entwerfen","設計"),("erbeuten","奪得"),
("erfahren","得知／經歷"),("erfassen","掌握"),("erfinden","發明"),
("erfolgen","發生"),("erfordern","需要"),("erfüllen","實現"),
("ergänzen","補充"),("ergeben","得出"),("erhalten","獲得"),
("erheben","徵收／升起"),("erholen","休養"),("erinnern","記得"),
("erkälten","感冒"),("erkennen","認出"),("erklären","說明"),
("erkunden","探勘"),("erlauben","允許"),("erleben","經歷"),
("erledigen","辦妥"),("ermöglichen","使可能"),("ernähren","餵養"),
("ernstnehmen","認真看待"),("erobern","征服"),("erreichen","達到"),
("erscheinen","出現"),("ersetzen","取代"),("ersparen","省下"),
("ersticken","窒息"),("ertragen","忍受"),("erwarten","期待"),
("erwähnen","提及"),("erwerben","取得"),("erzeugen","產生"),
("erziehen","教養"),("erzielen","達到"),("essen","吃"),
("existieren","存在"),("experimentieren","實驗"),("explodieren","爆炸"),
("exportieren","出口"),("fahren","行駛"),("fallen","掉落"),
("falten","摺疊"),("fangen","抓住"),("fassen","抓住／理解"),
("feiern","慶祝"),("fernhalten","遠離"),("fertigen","製造"),
("festlegen","訂定"),("feststellen","斷定"),("filmen","拍攝"),
("finanzieren","資助"),("finden","找到"),("fliegen","飛行"),
("fliehen","逃跑"),("fließen","流動"),("folgen","跟隨"),
("fordern","要求"),("fördern","促進"),("formen","塑造"),
("forschen","研究"),("fotografieren","拍照"),("fragen","詢問"),
("freilassen","釋放"),("freuen","高興"),("frieren","結凍"),
("frühstücken","吃早餐"),("fühlen","感覺"),("führen","領導"),
("füllen","填滿"),("fürchten","害怕"),("füttern","餵食"),
]
for word, zh in EXTRA_A2_VERBS:
    w(None, word, None, zh, "動詞", "A2")

EXTRA_A2_ADJ = [
("abhängig","依賴的"),("absolut","絕對的"),("aktiv","積極的"),
("aktuell","當前的"),("allgemein","一般的"),("allmählich","逐漸的"),
("alternativ","替代的"),("anders","不同的"),("angenehm","愉快的"),
("ansässig","定居的"),("ansteckend","傳染的"),("anstrengend","費力的"),
("verantwortlich","負責的"),("verdächtig","可疑的"),("verfügbar","可用的"),
("vergessen","被遺忘的"),("verheiratet","已婚的"),("verletzt","受傷的"),
("verliebt","戀愛的"),("verlässlich","可靠的"),("verrückt","瘋狂的"),
("verschieden","各種的"),("verständlich","可理解的"),("verwandt","有親戚關係的"),
("verzeihlich","可原諒的"),("vollständig","完整的"),("vorübergehend","暫時的"),
("wach","清醒的"),("wahr","真實的"),("wahrscheinlich","可能的"),
("warmherzig","熱忱的"),("wechselhaft","多變的"),("weich","軟的"),
("weit","遠的"),("weiter","進一步的"),("weltweit","全球的"),
("wertvoll","有價值的"),("wesentlichkeit","本質的"),("wesentlich","重要的"),
("wichtig","重要的"),("wild","野生的"),("willkommen","受歡迎的"),
("wirklich","真正的"),("wirtschaftlich","經濟的"),("wissbegierig","好學的"),
("witzig","風趣的"),("wohl","安好的"),("wunderbar","奇妙的"),
("wünschenswert","值得期望的"),("zentral","中央的"),("zufällig","偶然的"),
("zufrieden","滿意的"),("zugänglich","可接近的"),("zukünftig","未來的"),
("zulässig","允許的"),("zureichend","足夠的"),("zurückhaltend","保守的"),
("zusammenhängend","相關的"),("zuständig","主管的"),("zuverlässig","可靠的"),
("zweckmäßig","合目的的"),("zweifellos","無疑的"),("zwecklos","無用的"),
("üblich","常見的"),("überfüllt","過度擁擠的"),("überraschend","令人驚訝的"),
("übersichtlich","清楚的"),("übertreiben","誇大的"),("übrig","剩下的"),
("äußerlich","外表的"),("außerordentlich","非凡的"),("äußerst","極其"),
]
for word, zh in EXTRA_A2_ADJ:
    w(None, word, None, zh, "形容詞", "A2")


# ---------------- generate output ----------------

def slug(word: str) -> str:
    s = word.lower()
    rep = {"ä":"ae","ö":"oe","ü":"ue","ß":"ss"," ": "_","-":"_",".":"","/":"_","(":"",")":""}
    for a,b in rep.items():
        s = s.replace(a,b)
    s = re.sub(r"[^a-z0-9_]+","",s)
    return s[:48] or "w"

def approx_ipa(word: str) -> str:
    # lightweight readable pronunciation hint (not strict IPA)
    return word

# Rebuild with unique ids
entries = []
seen_ids = set()
seen_word_level = set()

for id_hint, article, word, plural, zh, cat, level in RAW:
    key = (word.lower(), level, article)
    if key in seen_word_level:
        continue
    seen_word_level.add(key)
    base_id = id_hint or slug(word)
    wid = base_id
    n = 2
    while wid in seen_ids:
        wid = f"{base_id}_{n}"
        n += 1
    seen_ids.add(wid)
    # examples
    if article:
        de = f"{article.capitalize()} {word} braucht man oft."
        zhex = f"{article} {word}（{zh}）很常用。"
        zhex = f"{article} {word}（{zh}）很常用。"
        if cat == "飲食":
            de = f"Ich mag {article} {word}."
            zhex = f"我喜歡{zh}。"
        elif cat in ("家庭","工作"):
            de = f"{article.capitalize()} {word} ist {zh}."
            zhex = f"{article} {word} 是{zh}。"
            de = f"Das ist {article} {word}."
            zhex = f"這是{zh}。"
        elif cat == "旅行":
            de = f"Wo ist {article} {word}?"
            zhex = f"{zh}在哪裡？"
            zhex = f"{zh}在哪裡？"
        elif cat == "自然":
            de = f"{article.capitalize()} {word} ist schön."
            zhex = f"{zh}很美。"
        elif cat == "時間":
            de = f"Wir treffen uns {('am ' + article + ' ' + word) if article=='der' else ('an der ' + word) if article=='die' else ('am ' + word)}."
            # simplify
            de = f"Heute sprechen wir über {article} {word}."
            zhex = f"今天我們談到{zh}。"
    else:
        if cat == "動詞":
            de = f"Kannst du {word}?"
            zhex = f"你會「{word}」（{zh}）嗎？"
        elif cat == "形容詞":
            de = f"Das ist {word}."
            zhex = f"那是{zh}。"
        elif cat == "數字":
            de = f"Ich zähle: {word}."
            zhex = f"我數：{zh}。"
        else:
            de = f"Was bedeutet {word}?"
            zhex = f"{word} 是什麼意思？是「{zh}」。"
            zhex = f"{word} 是什麼意思？是「{zh}」。"
    entries.append({
        "id": wid,
        "article": article,
        "word": word,
        "plural": plural,
        "translation": zh,
        "phonetic": approx_ipa(word),
        "category": cat,
        "example": de,
        "exampleTranslation": zhex,
        "level": level,
    })

a1 = sum(1 for e in entries if e["level"]=="A1")
a2 = sum(1 for e in entries if e["level"]=="A2")
print(f"COUNT A1={a1} A2={a2} total={len(entries)}")

out = Path("/agent/deutsch-vokabeln/src/data/vocabulary.ts")
lines = []
lines.append("export type Gender = 'der' | 'die' | 'das' | null")
lines.append("export type Level = 'A1' | 'A2'")
lines.append("""export type Category =
  | '日常'
  | '飲食'
  | '旅行'
  | '家庭'
  | '自然'
  | '工作'
  | '時間'
  | '動詞'
  | '形容詞'
  | '數字'

export interface VocabWord {
  id: string
  article: Gender
  word: string
  plural?: string
  translation: string
  phonetic: string
  category: Category
  example: string
  exampleTranslation: string
  level: Level
}

export const categories: Category[] = [
  '日常',
  '飲食',
  '旅行',
  '家庭',
  '自然',
  '工作',
  '時間',
  '動詞',
  '形容詞',
  '數字',
]

export const levels: Level[] = ['A1', 'A2']

export const vocabulary: VocabWord[] = [""")

for e in entries:
    art = "null" if e["article"] is None else json.dumps(e["article"])
    lines.append("  {")
    lines.append(f"    id: {json.dumps(e['id'])},")
    lines.append(f"    article: {art},")
    lines.append(f"    word: {json.dumps(e['word'], ensure_ascii=False)},")
    if e["plural"]:
        lines.append(f"    plural: {json.dumps(e['plural'], ensure_ascii=False)},")
    lines.append(f"    translation: {json.dumps(e['translation'], ensure_ascii=False)},")
    lines.append(f"    phonetic: {json.dumps(e['phonetic'], ensure_ascii=False)},")
    lines.append(f"    category: {json.dumps(e['category'], ensure_ascii=False)},")
    lines.append(f"    example: {json.dumps(e['example'], ensure_ascii=False)},")
    lines.append(f"    exampleTranslation: {json.dumps(e['exampleTranslation'], ensure_ascii=False)},")
    lines.append(f"    level: {json.dumps(e['level'])},")
    lines.append("  },")

lines.append("]")
lines.append("")
lines.append("export function countByLevel(level: Level): number {")
lines.append("  return vocabulary.filter((w) => w.level === level).length")
lines.append("}")
lines.append("")
out.write_text("\n".join(lines), encoding="utf-8")
print("wrote", out, "bytes", out.stat().st_size)
