/** Auto-generated by scripts/gen_vocab_path.py — 2-year vocab path. */
import raw from './vocabPath.json'

export type VocabPathDayKind = 'learn' | 'review'

export type VocabPathDay = {
  week: number
  day: number
  kind: VocabPathDayKind
  level: string
  titleZh: string
  vocabIds: string[]
  tipZh: string
}

export type VocabPathWeek = {
  week: number
  level: string
  phaseZh: string
  titleZh: string
  focusZh: string
  newCount: number
  days: VocabPathDay[]
}

export type VocabPathPhase = {
  fromWeek: number
  toWeek: number
  level: string
  titleZh: string
  focusZh: string
}

type File = {
  note: string
  meta: {
    weeks: number
    newPerDay: number
    studyDaysPerWeek: number
    wordsPerWeek: number
    totalNew: number
    phases: VocabPathPhase[]
  }
  weeks: VocabPathWeek[]
}

const data = raw as File

export const VOCAB_PATH_NOTE = data.note
export const VOCAB_PATH_META = data.meta
export const VOCAB_PATH_WEEKS: VocabPathWeek[] = data.weeks
export const VOCAB_PATH_PHASES: VocabPathPhase[] = data.meta.phases

export function getVocabPathWeek(week: number): VocabPathWeek | undefined {
  return VOCAB_PATH_WEEKS.find((w) => w.week === week)
}

export function getVocabPathDay(
  week: number,
  day: number,
): VocabPathDay | undefined {
  return getVocabPathWeek(week)?.days.find((d) => d.day === day)
}
