/** Auto-generated by scripts/gen_vocab_path.py — 2-year study path. */
import raw from './vocabPath.json'

export type VocabPathDayKind = 'learn' | 'review'

export type VocabPathDay = {
  week: number
  day: number
  kind: VocabPathDayKind
  level: string
  titleZh: string
  /** Index into VOCAB_PATH_PIPELINE for this day's scheduled start. */
  startIndex: number
  /** How many *new* (not-yet-learned) words to collect today. */
  targetCount: number
  /** Default slice (before skip/backfill). */
  vocabIds: string[]
  tipZh: string
  grammarId?: string
  grammarTitleZh?: string
  readingId?: string
  readingTitleZh?: string
  /** Review day: grammar touched this week */
  grammarIds?: string[]
  /** Review day: readings touched this week */
  readingIds?: string[]
}

export type VocabPathWeek = {
  week: number
  level: string
  phaseZh: string
  titleZh: string
  focusZh: string
  newPerDay: number
  newCount: number
  startIndex: number
  days: VocabPathDay[]
}

export type VocabPathPhase = {
  fromWeek: number
  toWeek: number
  level: string
  titleZh: string
  focusZh: string
  newPerDay: number
}

type File = {
  note: string
  meta: {
    weeks: number
    studyDaysPerWeek: number
    totalNew: number
    b2TargetWeek: number
    b2TargetDaysApprox: number
    newPerDayByPhase: Record<string, number>
    phases: VocabPathPhase[]
  }
  pipeline: string[]
  weeks: VocabPathWeek[]
}

const data = raw as File

export const VOCAB_PATH_NOTE = data.note
export const VOCAB_PATH_META = data.meta
export const VOCAB_PATH_WEEKS: VocabPathWeek[] = data.weeks
export const VOCAB_PATH_PHASES: VocabPathPhase[] = data.meta.phases
export const VOCAB_PATH_PIPELINE: string[] = data.pipeline

export function getVocabPathWeek(week: number): VocabPathWeek | undefined {
  return VOCAB_PATH_WEEKS.find((w) => w.week === week)
}

export function getVocabPathDay(
  week: number,
  day: number,
): VocabPathDay | undefined {
  return getVocabPathWeek(week)?.days.find((d) => d.day === day)
}

export type ResolvedVocabDay = {
  ids: string[]
  skippedIds: string[]
  /** True if pipeline ran out before filling targetCount. */
  shortfall: number
}

/**
 * Prefer fixed day.vocabIds. Kept for API compatibility — never auto-skips.
 */
export function resolveVocabDay(
  day: VocabPathDay,
  knownIds: Set<string> | ReadonlySet<string>,
): ResolvedVocabDay {
  void knownIds
  return {
    ids: [...day.vocabIds],
    skippedIds: [],
    shortfall: Math.max(0, day.targetCount - day.vocabIds.length),
  }
}
